#include "present_bridge.h"
#include <dxgi1_6.h>
#include <vector>
#include <cstdio>
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error(std::to_string(unsigned(h)));}
static ID3D12Resource*buf(ID3D12Device*d,UINT64 size,D3D12_HEAP_TYPE type){D3D12_HEAP_PROPERTIES hp{};hp.Type=type;D3D12_RESOURCE_DESC r{};r.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;r.Width=size;r.Height=1;r.DepthOrArraySize=r.MipLevels=1;r.SampleDesc.Count=1;r.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ID3D12Resource*p=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&r,type==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&p)));return p;}
int main(){try{IDXGIFactory6*f=nullptr;ck(CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;for(UINT i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 ad{};a->GetDesc1(&ad);if(ad.VendorId==0x1002&&wcsstr(ad.Description,L"9070"))D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}if(!d)throw std::runtime_error("9070 missing");ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));unsigned cases=0;
for(auto wh:{std::pair<UINT,UINT>{17,9},{128,32},{1920,1080}}){UINT w=wh.first,h=wh.second;D3D12_RESOURCE_DESC td{};td.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;td.Width=w;td.Height=h;td.DepthOrArraySize=td.MipLevels=1;td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_R10G10B10A2_UNORM;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;ID3D12Resource*t=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_COMMON,nullptr,IID_PPV_ARGS(&t)));D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};UINT64 size{};d->GetCopyableFootprints(&td,0,1,0,&fp,nullptr,nullptr,&size);auto*up=buf(d,size,D3D12_HEAP_TYPE_UPLOAD);auto*rb=buf(d,size,D3D12_HEAP_TYPE_READBACK);
 {Re9PresentBridge bridge;bridge.Create(q,w,h);NativeGameSubmission submit;submit.Create(q,false);
 for(unsigned pattern=0;pattern<2;pattern++){std::vector<unsigned>expected(size_t(w)*h);for(size_t i=0;i<expected.size();i++)expected[i]=pattern?unsigned(i*1664525u+1013904223u):unsigned((i&1023)|(((i*73)&1023)<<10)|(((i*397)&1023)<<20)|(((i/1024)&3)<<30));void*p=nullptr;D3D12_RANGE none{};ck(up->Map(0,&none,&p));for(UINT y=0;y<h;y++)memcpy(static_cast<char*>(p)+fp.Offset+size_t(y)*fp.Footprint.RowPitch,expected.data()+size_t(y)*w,w*4);up->Unmap(0,nullptr);
 for(int repeat=0;repeat<3;repeat++){
 submit.Submit([&](ID3D12GraphicsCommandList*c){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={t,0,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_DEST};c->ResourceBarrier(1,&b);D3D12_TEXTURE_COPY_LOCATION a{},u{};a.pResource=t;a.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;u.pResource=up;u.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;u.PlacedFootprint=fp;c->CopyTextureRegion(&a,0,0,0,&u,nullptr);std::swap(b.Transition.StateBefore,b.Transition.StateAfter);c->ResourceBarrier(1,&b);});submit.Flush();bridge.Read(t);bridge.Write(t);
 submit.Submit([&](ID3D12GraphicsCommandList*c){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={t,0,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_SOURCE};c->ResourceBarrier(1,&b);D3D12_TEXTURE_COPY_LOCATION a{},u{};a.pResource=rb;a.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;a.PlacedFootprint=fp;u.pResource=t;u.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;c->CopyTextureRegion(&a,0,0,0,&u,nullptr);std::swap(b.Transition.StateBefore,b.Transition.StateAfter);c->ResourceBarrier(1,&b);});submit.Flush();D3D12_RANGE read{0,size_t(size)};ck(rb->Map(0,&read,&p));size_t bad=0;for(UINT y=0;y<h;y++){auto*row=reinterpret_cast<unsigned*>(static_cast<char*>(p)+fp.Offset+size_t(y)*fp.Footprint.RowPitch);for(UINT x=0;x<w;x++)bad+=row[x]!=expected[size_t(y)*w+x];}rb->Unmap(0,&none);if(bad)throw std::runtime_error("roundtrip mismatch "+std::to_string(bad));cases++;}
 } }t->Release();up->Release();rb->Release();printf("roundtrip %ux%u OK\n",w,h);
}printf("PASS %u GPU roundtrips\n",cases);return 0;}catch(const std::exception&e){fprintf(stderr,"%s\n",e.what());return 1;}}
