#include "hip_d3d12_bridge.h"
#include "native_game_submission.h"
using namespace hip_reference;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static ID3D12Resource*buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE type){D3D12_HEAP_PROPERTIES hp{};hp.Type=type;D3D12_RESOURCE_DESC rd{};rd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;rd.Width=bytes;rd.Height=1;rd.DepthOrArraySize=rd.MipLevels=1;rd.SampleDesc.Count=1;rd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ID3D12Resource*r{};ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&rd,type==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void barrier(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER x{};x.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;x.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&x);}
int main(int argc,char**argv){try{if(argc!=6&&argc!=7){puts("bridge_network ASSETS MODULES INPUT_RGBA_F32 NOISE_F32 OUTPUT_RGB_F32 [900]");return 2;}Options o;o.assets=argv[1];o.modules=argv[2];o.wmma=o.wave=o.pooled=true;if(argc==7){if(std::string(argv[6])!="900")throw std::runtime_error("geometry");o.width=1600;o.height=1024;o.fast_vit=true;o.post_shift=3;}auto input=ReadBytes(argv[3]),nb=ReadBytes(argv[4]);if(input.size()!=size_t(o.width)*o.height*16||nb.size()!=50331648ull*4)throw std::runtime_error("input sizes");std::vector<float>noise(nb.size()/4);memcpy(noise.data(),nb.data(),nb.size());
 IDXGIFactory4*f{};ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d{};for(UINT i=0;;i++){IDXGIAdapter1*a{};if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002){ck(D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));}a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD adapter");ID3D12CommandQueue*q{};D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q,false);
 auto*upload=buffer(d,input.size(),D3D12_HEAP_TYPE_UPLOAD),*rgb=buffer(d,input.size(),D3D12_HEAP_TYPE_DEFAULT),*rb=buffer(d,size_t(o.width)*o.height*12,D3D12_HEAP_TYPE_READBACK);void*p{};D3D12_RANGE none{};ck(upload->Map(0,&none,&p));memcpy(p,input.data(),input.size());upload->Unmap(0,nullptr);submit.Submit([&](ID3D12GraphicsCommandList*c){c->CopyBufferRegion(rgb,0,upload,0,input.size());barrier(c,rgb,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});
 {D3D12Bridge bridge;bridge.Create(q,o,noise);for(unsigned i=0;i<3;i++){auto start=std::chrono::steady_clock::now();bridge.Run(submit,rgb,nullptr,0);submit.Flush();printf("bridge_iteration=%u wall_ms=%.6f\n",i,std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count());}auto*out=bridge.Output();size_t bytes=size_t(o.width)*o.height*12;submit.Submit([&](ID3D12GraphicsCommandList*c){barrier(c,out,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,out,0,bytes);barrier(c,out,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();D3D12_RANGE range{0,bytes};ck(rb->Map(0,&range,&p));std::ofstream result(argv[5],std::ios::binary);if(!result.write(static_cast<const char*>(p),bytes))throw std::runtime_error("output write");rb->Unmap(0,&none);}
 upload->Release();rgb->Release();rb->Release();q->Release();d->Release();puts("D3D12 -> HIP complete network -> D3D12, no experimental D3D features");return 0;}catch(const std::exception&e){fprintf(stderr,"bridge failed: %s\n",e.what());return 1;}}
