// Isolated production FAST3 FFN comparison; does not share an output filename with attention probes.
#define main unused_c32_validation_main
#include "c32_validate.cpp"
#undef main
extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
int main(int argc,char**argv){try{
 if(argc!=5&&argc!=6){puts("usage: c32_fast_ffn_validate.exe assets fast.hsaco fast3.cso prefix [map3]");return 2;}
 const bool map3=argc==6&&std::string(argv[5])=="map3";if(argc==6&&!map3)throw std::runtime_error("mode must be map3");
 clear_flags();auto fw=read(wide(argv[1])+L"\\block1-ffn.f32",8736);std::string prefix=argv[4];std::ofstream report(prefix+"-report.txt");
 std::ifstream shaderfile(argv[3],std::ios::binary|std::ios::ate);if(!shaderfile)throw std::runtime_error("oracle CSO missing");std::vector<char>code(size_t(shaderfile.tellg()));shaderfile.seekg(0);if(!shaderfile.read(code.data(),code.size()))throw std::runtime_error("oracle CSO read");
 std::vector<float>packed(27776/4,0);auto*bytes=reinterpret_cast<unsigned char*>(packed.data());memcpy(bytes+16384,fw.data()+8704,128);
 for(unsigned part=0;part<2;part++)for(unsigned i=0;i<4096;i++){float v=fw[(part?4608:512)+i];bool found=false;for(unsigned b=0;b<256;b++)if((b&127)<127&&fp8(b)==v){bytes[(part?16512:20608)+i]=static_cast<unsigned char>(b);found=true;break;}if(!found)throw std::runtime_error("matrix weight not FP8 exact");}
 if(map3){for(unsigned c=0;c<32;c++){float remaining=fw[8704+c];for(unsigned part=0;part<3;part++){unsigned best=0;double besterror=1e99;for(unsigned b=0;b<127;b++){double error=std::abs(double(std::abs(remaining))-fp8(b));if(error<besterror||(error==besterror&&!(b&1u))){best=b;besterror=error;}}if(remaining<0)best|=128;remaining-=fp8(best);bytes[24704+((c/16)*3+part)*512+c*16+c%16]=static_cast<unsigned char>(best);}}}
 const IID experimental={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&experimental,nullptr,nullptr));
 IDXGIFactory1*factory=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&factory)));ID3D12Device*d=nullptr;for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(factory->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}factory->Release();if(!d)throw std::runtime_error("AMD missing");
 ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q,false);
 D3D12_ROOT_PARAMETER params[6]{};for(unsigned i=0;i<4;i++){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;params[i].Descriptor.ShaderRegister=i;}params[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;params[5].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;params[5].Constants={0,0,13};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=6;rd.pParameters=params;
 ID3DBlob*b=nullptr,*error=nullptr;ck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&b,&error));if(error)error->Release();ID3D12RootSignature*root=nullptr;ck(d->CreateRootSignature(0,b->GetBufferPointer(),b->GetBufferSize(),IID_PPV_ARGS(&root)));b->Release();ID3D12PipelineState*pso=nullptr;D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={code.data(),code.size()};ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));
 const unsigned W=16,H=16,T=W*H,raw_output=1;std::vector<ID3D12Resource*>owned;
 auto upload=[&](const std::vector<float>&v){auto*r=buffer(d,v.size()*4,D3D12_HEAP_TYPE_UPLOAD);owned.push_back(r);void*m=nullptr;D3D12_RANGE none{};ck(r->Map(0,&none,&m));memcpy(m,v.data(),v.size()*4);r->Unmap(0,nullptr);return r;};
 auto*weights=upload(packed);auto*source=upload(std::vector<float>(T*32));auto*rb=buffer(d,T*32*4,D3D12_HEAP_TYPE_READBACK);owned.push_back(rb);
 D3D12_RESOURCE_DESC od=source->GetDesc();od.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;ID3D12Resource*out=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));owned.push_back(out);
 hip_probe::Api hip;hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle module{},expand{},contract{};hip.Check(hip.hipModuleLoad(&module,argv[2]),"module");hip.Check(hip.hipModuleGetFunction(&expand,module,"c32_ffn_expand_fast"),"expand");hip.Check(hip.hipModuleGetFunction(&contract,module,map3?"c32_ffn_contract_fast_map3":"c32_ffn_contract_fast"),"contract");
 std::vector<void*>allocations;auto alloc=[&](size_t n){void*p=nullptr;hip.Check(hip.hipMalloc(&p,n*4),"alloc");allocations.push_back(p);return p;};void*di=alloc(T*32),*dw=alloc(8736),*dh=alloc(T*128),*dout=alloc(T*32);hip.Check(hip.hipMemcpy(dw,fw.data(),fw.size()*4,1),"weights upload");size_t bitdiff=0,invalid=0;
 for(unsigned pattern=0;pattern<3;pattern++){
  std::vector<float>input(T*32);for(unsigned i=0;i<input.size();i++)input[i]=pattern==0?fp8(((i*37+11)%96)|((i%3==0)?128:0)):pattern==1?float(int((i*73+19)%2048)-1024)/512.f:float(int((i*17+31)%2048)-1024);
  std::string tag=prefix+"-p"+std::to_string(pattern);save(tag+"-input.f32",input);void*m=nullptr;D3D12_RANGE none{};ck(source->Map(0,&none,&m));memcpy(m,input.data(),input.size()*4);source->Unmap(0,nullptr);
  unsigned constants[13]={0,W,H,0,0,map3?3u:0u,W,H,0,0,0,0,W};
  submit.Submit([&](ID3D12GraphicsCommandList*c){c->SetComputeRootSignature(root);c->SetPipelineState(pso);c->SetComputeRootShaderResourceView(0,weights->GetGPUVirtualAddress());for(unsigned i=1;i<4;i++)c->SetComputeRootShaderResourceView(i,source->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(4,out->GetGPUVirtualAddress());c->SetComputeRoot32BitConstants(5,13,constants,0);c->Dispatch(T/16,1,1);transition(c,out,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,out,0,T*32*4);transition(c,out,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);});submit.Flush();
  std::vector<float>oracle(T*32),actual(T*32),hidden(T*128);D3D12_RANGE range{0,T*32*4};ck(rb->Map(0,&range,&m));memcpy(oracle.data(),m,T*32*4);rb->Unmap(0,&none);
  hip.Check(hip.hipMemcpy(di,input.data(),input.size()*4,1),"input");hip.Check(hip.hipMemsetAsync(dout,0xff,T*32*4,nullptr),"sentinel");void*ea[]={&di,&dw,&dh,(void*)&T};void*ca[]={&di,&dh,&dw,&dout,(void*)&T,(void*)&raw_output};hip.Check(hip.hipModuleLaunchKernel(expand,((T+63)/64)*2,1,1,512,1,1,0,nullptr,ea,nullptr),"expand launch");hip.Check(hip.hipModuleLaunchKernel(contract,(T+63)/64,1,1,256,1,1,0,nullptr,ca,nullptr),"contract launch");hip.Check(hip.hipDeviceSynchronize(),"completion");hip.Check(hip.hipMemcpy(actual.data(),dout,T*32*4,2),"output");hip.Check(hip.hipMemcpy(hidden.data(),dh,T*128*4,2),"hidden");
  unsigned debug_mode=2;ca[5]=&debug_mode;hip.Check(hip.hipModuleLaunchKernel(contract,(T+63)/64,1,1,256,1,1,0,nullptr,ca,nullptr),"contract pre-round diagnostic");hip.Check(hip.hipDeviceSynchronize(),"diagnostic completion");std::vector<float>pre_round(T*32);hip.Check(hip.hipMemcpy(pre_round.data(),dout,T*32*4,2),"pre-round read");save(tag+"-hip-pre-round.f32",pre_round);
  save(tag+"-hlsl-fast3.f32",oracle);save(tag+"-hip-fast.f32",actual);save(tag+"-hip-hidden.f32",hidden);auto r=compare(oracle,actual);bitdiff+=r.bits;invalid+=r.invalid;printf("pattern=%u count=%zu bitdiff=%zu numericdiff=%zu invalid=%zu maxabs=%.9g\n",pattern,actual.size(),r.bits,r.numeric,r.invalid,r.maxabs);report<<"pattern="<<pattern<<" bitdiff="<<r.bits<<" numericdiff="<<r.numeric<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";fflush(stdout);
 }
 hip.Check(hip.hipDeviceSynchronize(),"final sync");for(auto*p:allocations)hip.Check(hip.hipFree(p),"free");hip.Check(hip.hipModuleUnload(module),"unload");submit.Flush();for(auto*r:owned)r->Release();pso->Release();root->Release();q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",bitdiff,invalid);return invalid?1:bitdiff?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
