// Usage: c32_validate.exe ASSETS_DIR MODULE_HSACO OUTPUT_PREFIX
// Scalar D3D12 NativePreblockRuntime oracle vs SDKless HIP C32 stages. No deployment.
#include <cmath>
#include <windows.h>
#include <dxgi1_6.h>
#include <d3d12.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include "hip_api.h"
#include "../../src/native_lab_paths.h"
#include "../../src/native_game_submission.h"
using hip_probe::Handle;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::wstring wide(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,nullptr,0);std::wstring v(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s,-1,v.data(),n);v.resize(n-1);return v;}
static std::vector<float> read(const std::wstring&p,size_t count){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("weight missing/size");f.seekg(0);std::vector<float>v(count);if(!f.read(reinterpret_cast<char*>(v.data()),count*4))throw std::runtime_error("weight read");return v;}
static void save(const std::string&p,const std::vector<float>&v){std::ofstream f(p,std::ios::binary);if(!f.write(reinterpret_cast<const char*>(v.data()),v.size()*4))throw std::runtime_error("save failed "+p);}
static ID3D12Resource* buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE heap){D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;desc.Width=bytes;desc.Height=1;desc.DepthOrArraySize=desc.MipLevels=1;desc.SampleDesc.Count=1;desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;if(heap==D3D12_HEAP_TYPE_DEFAULT)desc.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&desc,heap==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void transition(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
static void clear_flags(){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){const wchar_t*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)_wputenv((n+L"=").c_str());}
static float fp8(unsigned b){unsigned e=(b>>3)&15,m=b&7;float x=e?std::ldexp(1.f+m/8.f,int(e)-7):m/512.f;return b&128?-x:x;}
struct Comparison {size_t bits{},numeric{},invalid{};double maxabs{};};
static Comparison compare(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())throw std::runtime_error("compare size");Comparison r;for(size_t i=0;i<a.size();i++){unsigned x,y;memcpy(&x,&a[i],4);memcpy(&y,&b[i],4);r.bits+=x!=y;r.numeric+=a[i]!=b[i];r.invalid+=!std::isfinite(a[i])||!std::isfinite(b[i]);if(std::isfinite(a[i])&&std::isfinite(b[i]))r.maxabs=std::max(r.maxabs,std::abs(double(a[i])-b[i]));}return r;}

extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
int main(int argc,char**argv){try{
 if(argc!=5){puts("Usage: c32_fast_attention_validate.exe ASSETS HIP_MODULE ORACLE_CSO OUTPUT_PREFIX");return 2;}clear_flags();auto dir=wide(argv[1]);auto aw=NativeReadF32(dir+L"\\block1-attention.f32","fast attention weights");if(aw.size()!=8225)throw std::runtime_error("attention weights size");std::vector<unsigned char>packed(28928,0);memcpy(packed.data()+8192,aw.data()+4096,4096*4);memcpy(packed.data()+24576,aw.data()+8192,33*4);auto encode=[&](float v){for(unsigned b=0;b<256;b++)if((b&127)<127&&fp8(b)==v)return static_cast<unsigned char>(b);throw std::runtime_error("non-FP8 matrix weight");};for(unsigned i=0;i<1024;i++)packed[24832+i]=encode(aw[3072+i]);for(unsigned i=0;i<3072;i++)packed[25856+i]=encode(aw[i]);
 const IID exp={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&exp,nullptr,nullptr));IDXGIFactory1*f=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD device missing");ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q,false);
 auto upload=[&](const void*p,size_t n){auto*r=buffer(d,n,D3D12_HEAP_TYPE_UPLOAD);void*m;D3D12_RANGE none{};ck(r->Map(0,&none,&m));memcpy(m,p,n);r->Unmap(0,nullptr);return r;};auto*dw=upload(packed.data(),packed.size());D3D12_ROOT_PARAMETER params[5]{};for(unsigned i=0;i<4;i++){params[i].ParameterType=i<2?D3D12_ROOT_PARAMETER_TYPE_SRV:D3D12_ROOT_PARAMETER_TYPE_UAV;params[i].Descriptor={i%2,0};}params[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;params[4].Constants={0,0,5};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=5;rd.pParameters=params;ID3DBlob*blob=nullptr,*error=nullptr;ck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&error));ID3D12RootSignature*root=nullptr;ck(d->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),IID_PPV_ARGS(&root)));blob->Release();if(error)error->Release();ck(D3DReadFileToBlob(wide(argv[3]).c_str(),&blob));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));blob->Release();
 hip_probe::Api hip(7);hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle module=nullptr;hip.Check(hip.hipModuleLoad(&module,argv[2]),"module");std::vector<void*>allocs;auto alloc=[&](size_t n){void*p;hip.Check(hip.hipMalloc(&p,n*4),"malloc");allocs.push_back(p);return p;};unsigned T=256,windows=4,raw=1;void*hi=alloc(T*32),*hw=alloc(aw.size()),*qkv=alloc(T*96),*norm=alloc(T*96),*ex=alloc(windows*4096),*prob=alloc(windows*4096),*av=alloc(T*32),*out=alloc(T*32);hip.Check(hip.hipMemcpy(hw,aw.data(),aw.size()*4,1),"weight upload");auto launch=[&](const char*name,unsigned n,std::initializer_list<void*>args){Handle fn;hip.Check(hip.hipModuleGetFunction(&fn,module,name),name);std::vector<void*>a(args);hip.Check(hip.hipModuleLaunchKernel(fn,(n+255)/256,1,1,32,1,1,0,nullptr,a.data(),nullptr),name);hip.Check(hip.hipDeviceSynchronize(),name);};std::string prefix=argv[4];std::ofstream report(prefix+"-report.txt");size_t bitdiff=0,invalid=0;
 for(unsigned pattern=0;pattern<2;pattern++){std::string base=prefix+"-p"+std::to_string(pattern);std::vector<float>input(T*32);for(unsigned i=0;i<input.size();i++)input[i]=pattern?float(int((i*73+19)%2048)-1024)/512.f:fp8(((i*37+11)%96)|((i%3==0)?128:0));save(base+"-input.f32",input);auto*di=upload(input.data(),input.size()*4),*dr=buffer(d,input.size()*4,D3D12_HEAP_TYPE_DEFAULT),*da=buffer(d,T*96*4,D3D12_HEAP_TYPE_DEFAULT),*rb=buffer(d,T*96*4,D3D12_HEAP_TYPE_READBACK);std::vector<float>oracle;std::vector<std::vector<float>>stages(6);
 for(unsigned debug=0;debug<6;debug++){size_t count=debug==1||debug==2?T*96:debug==3||debug==4?T*64:T*32;submit.Submit([&](ID3D12GraphicsCommandList*c){if(!debug){transition(c,dr,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);transition(c,da,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);}c->SetComputeRootSignature(root);c->SetPipelineState(pso);c->SetComputeRootShaderResourceView(0,dw->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,di->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(2,dr->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(3,da->GetGPUVirtualAddress());unsigned constants[]={0,16,16,debug,0};c->SetComputeRoot32BitConstants(4,5,constants,0);c->Dispatch((windows+1)/2,1,1);auto*r=debug?da:dr;transition(c,r,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,r,0,count*4);transition(c,r,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);});submit.Flush();void*m;D3D12_RANGE rr{0,count*4};ck(rb->Map(0,&rr,&m));stages[debug].resize(count);memcpy(stages[debug].data(),m,count*4);rb->Unmap(0,nullptr);const char*names[]={"out","qkv","norm","ex","prob","av"};save(base+"-d3d-"+names[debug]+".f32",stages[debug]);}oracle=stages[0];rb->Release();da->Release();dr->Release();di->Release();
 hip.Check(hip.hipMemcpy(hi,input.data(),input.size()*4,1),"input upload");for(auto p:{std::pair<void*,size_t>{qkv,T*96},{norm,T*96},{ex,windows*4096},{prob,windows*4096},{av,T*32},{out,T*32}})hip.Check(hip.hipMemsetAsync(p.first,0xff,p.second*4,nullptr),"sentinel");launch("c32_fast_qkv",T*96,{&hi,&hw,&qkv,&T});launch("c32_fast_normalize",T*96,{&qkv,&hw,&norm,&T});launch("c32_fast_scores",windows*4096,{&norm,&hw,&ex,&windows});launch("c32_fast_probabilities",windows*4096,{&ex,&prob,&windows});launch("c32_fast_av",T*32,{&prob,&norm,&av,&windows});launch("c32_fast_project",T*32,{&av,&hi,&hw,&out,&T,&raw});for(auto p:{std::pair<const char*,std::pair<void*,size_t>>{"qkv",{qkv,T*96}},{"norm",{norm,T*96}},{"ex",{ex,windows*4096}},{"prob",{prob,windows*4096}},{"av",{av,T*32}},{"out",{out,T*32}}}){std::vector<float>v(p.second.second);hip.Check(hip.hipMemcpy(v.data(),p.second.first,v.size()*4,2),"read");save(base+"-hip-"+p.first+".f32",v);for(float a:v)invalid+=!std::isfinite(a);{unsigned si=!strcmp(p.first,"qkv")?1:!strcmp(p.first,"norm")?2:!strcmp(p.first,"ex")?3:!strcmp(p.first,"prob")?4:!strcmp(p.first,"av")?5:0;auto c=compare(stages[si],v);bitdiff+=c.bits;invalid+=c.invalid;printf("pattern=%u stage=%s bitdiff=%zu numericdiff=%zu invalid=%zu maxabs=%.9g\n",pattern,p.first,c.bits,c.numeric,c.invalid,c.maxabs);report<<"pattern="<<pattern<<" stage="<<p.first<<" bitdiff="<<c.bits<<" numericdiff="<<c.numeric<<" invalid="<<c.invalid<<" maxabs="<<c.maxabs<<"\n";}}fflush(stdout);
 }
 for(void*p:allocs)hip.Check(hip.hipFree(p),"free");hip.Check(hip.hipModuleUnload(module),"unload");pso->Release();root->Release();dw->Release();q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",bitdiff,invalid);return invalid?1:bitdiff?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
