#define main unused_c32_validation_main
#include "c32_validate.cpp"
#undef main
// ASSETS FFN_MODULE SIX_ATTENTION_MODULE FUSED_MODULE OUTPUT_PREFIX [repeats20]
int main(int argc,char**argv){try{
 if(argc<6||argc>7){puts("usage: c32_fused_ffn_attention_validate.exe assets ffn.hsaco attention.hsaco fused.hsaco prefix [repeats]");return 2;}clear_flags();unsigned repeats=argc==7?unsigned(std::stoul(argv[6])):20;if(!repeats||repeats>1000)throw std::runtime_error("repeat range");std::string prefix=argv[5];std::ofstream report(prefix+"-report.txt");hip_probe::Api hip;hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle modules[3]{};for(unsigned i=0;i<3;i++)hip.Check(hip.hipModuleLoad(&modules[i],argv[i+2]),"module");Handle expand{},contract[2]{},af[6]{},fused{};hip.Check(hip.hipModuleGetFunction(&expand,modules[0],"c32_ffn_expand_fast"),"expand");hip.Check(hip.hipModuleGetFunction(&contract[0],modules[0],"c32_ffn_contract_fast"),"contract0");hip.Check(hip.hipModuleGetFunction(&contract[1],modules[0],"c32_ffn_contract_fast_map3"),"contract3");const char*an[]={"c32_fast_qkv","c32_fast_normalize","c32_fast_scores","c32_fast_probabilities","c32_fast_av","c32_fast_project"};for(unsigned i=0;i<6;i++)hip.Check(hip.hipModuleGetFunction(&af[i],modules[1],an[i]),"attention function");hip.Check(hip.hipModuleGetFunction(&fused,modules[2],"c32_fast_ffn_attention_fused"),"fused");
 using EC=int(*)(Handle*,unsigned);using ER=int(*)(Handle,Handle);using ES=int(*)(Handle);using EE=int(*)(float*,Handle,Handle);EC ec{};ER er{};ES es{},ed{};EE ee{};hip.Load(ec,"hipEventCreateWithFlags");hip.Load(er,"hipEventRecord");hip.Load(es,"hipEventSynchronize");hip.Load(ed,"hipEventDestroy");hip.Load(ee,"hipEventElapsedTime");Handle start{},stop{};hip.Check(ec(&start,0),"event");hip.Check(ec(&stop,0),"event");size_t totaldiff=0,invalid=0;
 for(unsigned block:{1u,4u})for(unsigned T:{256u,4096u}){
  auto fw=read(wide(argv[1])+L"\\block"+std::to_wstring(block)+L"-ffn.f32",8736),aw=read(wide(argv[1])+L"\\block"+std::to_wstring(block)+L"-attention.f32",8225);unsigned windows=T/64,raw=1;std::vector<void*>owned;auto alloc=[&](size_t n){void*p=nullptr;hip.Check(hip.hipMalloc(&p,n*4),"malloc");owned.push_back(p);return p;};void*di=alloc(T*32),*dfw=alloc(8736),*daw=alloc(8225),*hidden=alloc(T*128),*ffn=alloc(T*32),*qkv=alloc(T*96),*norm=alloc(T*96),*ex=alloc(T*64),*prob=alloc(T*64),*av=alloc(T*32),*out=alloc(T*32),*fo=alloc(T*32);hip.Check(hip.hipMemcpy(dfw,fw.data(),fw.size()*4,1),"fw");hip.Check(hip.hipMemcpy(daw,aw.data(),aw.size()*4,1),"aw");
  for(unsigned pattern=0;pattern<2;pattern++)for(unsigned mode:{0u,3u}){
   std::vector<float>input(T*32);for(unsigned i=0;i<input.size();i++)input[i]=pattern?float(int((i*73+19)%2048)-1024)/512.f:fp8(((i*37+11)%96)|((i%3==0)?128:0));hip.Check(hip.hipMemcpy(di,input.data(),input.size()*4,1),"input");
   auto run=[&](bool use_fused){if(use_fused){void*a[]={&di,&dfw,&daw,&fo,&windows,&mode,&raw};hip.Check(hip.hipModuleLaunchKernel(fused,windows,1,1,128,1,1,0,nullptr,a,nullptr),"fused launch");return;}
    void*ea[]={&di,&dfw,&hidden,&T};void*ca[]={&di,&hidden,&dfw,&ffn,&T,&raw};hip.Check(hip.hipModuleLaunchKernel(expand,((T+63)/64)*2,1,1,512,1,1,0,nullptr,ea,nullptr),"expand launch");hip.Check(hip.hipModuleLaunchKernel(contract[mode==3],(T+63)/64,1,1,256,1,1,0,nullptr,ca,nullptr),"contract launch");
    void*a0[]={&ffn,&daw,&qkv,&T};void*a1[]={&qkv,&daw,&norm,&T};void*a2[]={&norm,&daw,&ex,&windows};void*a3[]={&ex,&prob,&windows};void*a4[]={&prob,&norm,&av,&windows};void*a5[]={&av,&ffn,&daw,&out,&T,&raw};void**args[]={a0,a1,a2,a3,a4,a5};unsigned work[]={T*96,T*96,T*64,T*64,T*32,T*32};for(unsigned j=0;j<6;j++)hip.Check(hip.hipModuleLaunchKernel(af[j],(work[j]+255)/256,1,1,32,1,1,0,nullptr,args[j],nullptr),"attention launch");};
   for(void*p:{out,fo})hip.Check(hip.hipMemsetAsync(p,0xff,T*32*4,nullptr),"sentinel");run(false);run(true);hip.Check(hip.hipDeviceSynchronize(),"completion");std::vector<float>a(T*32),b(T*32),f(T*32);hip.Check(hip.hipMemcpy(a.data(),out,a.size()*4,2),"chain read");hip.Check(hip.hipMemcpy(b.data(),fo,b.size()*4,2),"fused read");hip.Check(hip.hipMemcpy(f.data(),ffn,f.size()*4,2),"ffn read");auto c=compare(a,b);totaldiff+=c.bits;invalid+=c.invalid;std::string tag=prefix+"-b"+std::to_string(block)+"-t"+std::to_string(T)+"-p"+std::to_string(pattern)+"-m"+std::to_string(mode);save(tag+"-chain.f32",a);save(tag+"-fused.f32",b);save(tag+"-ffn.f32",f);printf("block=%u tokens=%u pattern=%u mode=%u bitdiff=%zu invalid=%zu maxabs=%.9g\n",block,T,pattern,mode,c.bits,c.invalid,c.maxabs);report<<"block="<<block<<" tokens="<<T<<" pattern="<<pattern<<" mode="<<mode<<" bitdiff="<<c.bits<<" invalid="<<c.invalid<<" maxabs="<<c.maxabs<<"\n";
   if(block==4&&T==4096&&pattern==1){for(bool use_fused:{false,true}){for(unsigned i=0;i<3;i++)run(use_fused);hip.Check(er(start,nullptr),"start");for(unsigned i=0;i<repeats;i++)run(use_fused);hip.Check(er(stop,nullptr),"stop");hip.Check(es(stop),"sync event");float ms=0;hip.Check(ee(&ms,start,stop),"elapsed");printf("TIME mode=%u fused=%u tokens=%u mean_ms=%.6f\n",mode,unsigned(use_fused),T,ms/repeats);report<<"TIME mode="<<mode<<" fused="<<use_fused<<" tokens="<<T<<" mean_ms="<<ms/repeats<<"\n";}}
   fflush(stdout);
  }
  hip.Check(hip.hipDeviceSynchronize(),"finish");for(auto*p:owned)hip.Check(hip.hipFree(p),"free");
 }
 hip.Check(ed(start),"destroy event");hip.Check(ed(stop),"destroy event");for(auto m:modules)hip.Check(hip.hipModuleUnload(m),"unload");printf("RESULT bitdiff=%zu invalid=%zu\n",totaldiff,invalid);return invalid?1:totaldiff?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
