// Usage: deep_validate.exe ASSETS_DIR MODULE_HSACO OUTPUT_PREFIX
// Scalar D3D12 NativeVitBlock oracle vs SDKless HIP ViT64 stages. No deployment.
#include <cmath>
#include <windows.h>
#include <dxgi1_6.h>
#include <d3d12.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include "hip_api.h"
#include "../../src/native_vit_block.h"
#include "../../src/native_game_submission.h"
#include "../../src/native_lab_paths.h"
using hip_probe::Handle;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::wstring wide(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,nullptr,0);std::wstring v(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s,-1,v.data(),n);v.resize(n-1);return v;}
static std::vector<float> read(const std::wstring&p,size_t count){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("weight missing/size");f.seekg(0);std::vector<float>v(count);if(!f.read(reinterpret_cast<char*>(v.data()),count*4))throw std::runtime_error("weight read");return v;}
static void save(const std::string&p,const std::vector<float>&v){std::ofstream f(p,std::ios::binary);if(!f.write(reinterpret_cast<const char*>(v.data()),v.size()*4))throw std::runtime_error("save failed "+p);}
static ID3D12Resource* buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE heap){D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;desc.Width=bytes;desc.Height=1;desc.DepthOrArraySize=desc.MipLevels=1;desc.SampleDesc.Count=1;desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;if(heap==D3D12_HEAP_TYPE_DEFAULT)desc.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&desc,heap==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void transition(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
static void clear_flags(){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){const wchar_t*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)_wputenv((n+L"=").c_str());}
static float fp8(unsigned b){unsigned e=(b>>3)&15,m=b&7;float x=e?std::ldexp(1.f+m/8.f,int(e)-7):m/512.f;return b&128?-x:x;}
struct Comparison {size_t bits{},numeric{},invalid{};double maxabs{};};
static Comparison compare(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())throw std::runtime_error("compare size");Comparison r;for(size_t i=0;i<a.size();i++){unsigned x,y;memcpy(&x,&a[i],4);memcpy(&y,&b[i],4);r.bits+=x!=y;r.numeric+=a[i]!=b[i];r.invalid+=!std::isfinite(a[i])||!std::isfinite(b[i]);if(std::isfinite(a[i])&&std::isfinite(b[i]))r.maxabs=std::max(r.maxabs,std::abs(double(a[i])-b[i]));}return r;}

extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
static void loadflags(const wchar_t*path){clear_flags();std::ifstream f(path);if(!f)throw std::runtime_error("flags missing");std::string s;while(std::getline(f,s)){auto p=s.find_first_not_of(" \t\r");if(p==std::string::npos||s[p]=='#')continue;s=s.substr(p);auto eq=s.find('=');if(eq==std::string::npos||s.rfind("DLSS5_",0))continue;auto k=s.substr(0,eq),v=s.substr(eq+1);while(!v.empty()&&(v.back()=='\r'||v.back()==' '))v.pop_back();std::wstring wk(k.begin(),k.end()),wv(v.begin(),v.end());_putenv_s(k.c_str(),v.c_str());_wputenv_s(wk.c_str(),wv.c_str());}}
int main(int argc,char**argv){try{
 if(argc!=5&&argc!=6&&argc!=7){puts("Usage: deep_fast_validate.exe ASSETS FLAGS DEEP_FAST_HSACO OUTPUT_PREFIX [tokens=64|240|400|640] [SPLIT_ORACLE_CSO]");return 2;}auto dir=wide(argv[1]);loadflags(wide(argv[2]).c_str());auto load=[&](const wchar_t*n){return NativeReadF32(dir+L"\\"+n,"ViT fast weights");};auto ew=load(L"block31-expand.f32"),cw=load(L"block31-contract.f32"),qw=load(L"block31-qkv.f32"),pw=load(L"block31-projection.f32");const IID exp={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&exp,nullptr,nullptr));IDXGIFactory1*f=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD missing");ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q,false);
 auto upload=[&](const std::vector<float>&v){auto*r=buffer(d,v.size()*4,D3D12_HEAP_TYPE_UPLOAD);void*p;D3D12_RANGE rr{};ck(r->Map(0,&rr,&p));memcpy(p,v.data(),v.size()*4);r->Unmap(0,nullptr);return r;};auto readback=[&](ID3D12Resource*r){size_t n=r->GetDesc().Width;auto*rb=buffer(d,n,D3D12_HEAP_TYPE_READBACK);submit.Submit([&](ID3D12GraphicsCommandList*c){transition(c,r,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,r,0,n);transition(c,r,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();void*p;D3D12_RANGE rr{0,n};ck(rb->Map(0,&rr,&p));std::vector<unsigned char>b(n);memcpy(b.data(),p,n);rb->Unmap(0,nullptr);rb->Release();return b;};auto linear=[&](NativeVitLinear&l){NativeResidentFlush();for(unsigned c=0;c<l.ChunkCount();c++){submit.Submit([&](ID3D12GraphicsCommandList*x){l.RecordChunk(x,c);});submit.Flush();}};
 hip_probe::Api hip(7);hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle module;hip.Check(hip.hipModuleLoad(&module,argv[3]),"module");std::vector<void*>allocs;auto alloc=[&](size_t n){void*p;hip.Check(hip.hipMalloc(&p,n*4),"alloc");allocs.push_back(p);return p;};auto hu=[&](const std::vector<float>&v){void*p=alloc(v.size());hip.Check(hip.hipMemcpy(p,v.data(),v.size()*4,1),"upload");return p;};void*he=hu(ew),*hc=hu(cw),*hq=hu(qw),*hp=hu(pw);unsigned T=argc>=6?unsigned(std::stoul(argv[5])):64,C=1024,E=4096;if(T!=64&&T!=240&&T!=400&&T!=640)throw std::runtime_error("tokens");void*hi=alloc(T*C),*hidden=alloc(T*E),*contract=alloc(T*C),*qkv=alloc(T*3072),*norm=alloc(T*3072),*proj=alloc(T*C),*ex=alloc(size_t(T)*32*T),*inv=alloc(T*32),*av=alloc(T*C);auto run=[&](const char*n,unsigned work,std::initializer_list<void*>args){Handle fn;hip.Check(hip.hipModuleGetFunction(&fn,module,n),n);std::vector<void*>a(args);hip.Check(hip.hipModuleLaunchKernel(fn,(work+255)/256,1,1,32,1,1,0,nullptr,a.data(),nullptr),n);hip.Check(hip.hipDeviceSynchronize(),n);};std::string prefix=argv[4];std::ofstream report(prefix+"-report.txt");size_t total=0,bad=0;
 for(unsigned pat=0;pat<2;pat++){std::string base=prefix+"-p"+std::to_string(pat);std::vector<float>input(T*C);for(unsigned i=0;i<input.size();i++)input[i]=pat?fp8(((i*73+19)%88)|((i%5<2)?128:0)):fp8(((i*37+11)%96)|((i%3==0)?128:0));auto*di=upload(input);hip.Check(hip.hipMemcpy(hi,input.data(),input.size()*4,1),"input upload");auto check=[&](const char*n,void*p,const std::vector<float>&oracle){std::vector<float>v(oracle.size());hip.Check(hip.hipMemcpy(v.data(),p,v.size()*4,2),"read HIP");save(base+"-hip-"+n+".f32",v);save(base+"-d3d-"+n+".f32",oracle);auto r=compare(oracle,v);total+=r.bits;bad+=r.invalid;printf("pattern=%u stage=%s count=%zu bitdiff=%zu numericdiff=%zu invalid=%zu maxabs=%.9g\n",pat,n,v.size(),r.bits,r.numeric,r.invalid,r.maxabs);report<<"pattern="<<pat<<" stage="<<n<<" bitdiff="<<r.bits<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";};
 {NativeVitLinear expand;expand.Create(d,di,nullptr,T,C,E,true,ew,dir);linear(expand);auto b=readback(expand.Output());// NativeVitLinear retains a4-byte-per-element allocation even when the
 // production shader writes only a tiled E4M3 byte payload. Read that prefix.
 if(b.size()<size_t(T)*E||!_wgetenv(L"DLSS5_FP8_HIDDEN")||wcscmp(_wgetenv(L"DLSS5_FP8_HIDDEN"),L"1")||!_wgetenv(L"DLSS5_VIT_TILED")||wcscmp(_wgetenv(L"DLSS5_VIT_TILED"),L"1"))throw std::runtime_error("requires production tiled FP8 hidden payload");std::vector<float>oracle(T*E);for(unsigned t=0;t<T;t++)for(unsigned c=0;c<E;c++)oracle[t*E+c]=fp8(b[((t/16)*128+c/32)*512+(t%16)*32+c%32]);run("vit_expand",T*E,{&hi,&he,&hidden,&T,&C,&E});check("expand",hidden,oracle);
  // Isolate contract by supplying the SAME HLSL hidden values to HIP.
  hip.Check(hip.hipMemcpy(hidden,oracle.data(),oracle.size()*4,1),"isolated hidden upload");NativeVitLinear reduce;reduce.Create(d,expand.Output(),di,T,E,C,false,cw,dir);linear(reduce);auto br=readback(reduce.Output());std::vector<float>r(T*C);if(br.size()!=r.size()*4)throw std::runtime_error("contract size");memcpy(r.data(),br.data(),br.size());run("vit_project",T*C,{&hidden,&hc,&hi,&contract,&T,&E,&C});check("contract",contract,r);
 }
 {NativeVitQkv stage;stage.Create(d,di,T,qw,dir);if(!stage.Fused())throw std::runtime_error("production fused QKV required");NativeResidentFlush();submit.Submit([&](ID3D12GraphicsCommandList*c){stage.Record(c);});submit.Flush();auto b=readback(stage.Packed8());std::vector<float>r(T*3072);if(b.size()!=r.size())throw std::runtime_error("QKV8 size");for(size_t i=0;i<r.size();i++)r[i]=fp8(b[i]);run("vit_qkv_project",T*3072,{&hi,&hq,&qkv,&T});run("vit_qkv_normalize",T*3072,{&qkv,&hq,&norm,&T});check("qkv-normalized",norm,r);
  hip.Check(hip.hipMemcpy(norm,r.data(),r.size()*4,1),"isolated attention input");NativeVitAttention attention;attention.Create(d,stage.Packed8(),T,dir,true);NativeResidentFlush();submit.Submit([&](ID3D12GraphicsCommandList*c){attention.Record(c);});submit.Flush();auto ab=readback(attention.Output());std::vector<float>ar(T*C);if(ab.size()!=ar.size()*4)throw std::runtime_error("attention size");memcpy(ar.data(),ab.data(),ab.size());run("vit_attention_scores_fast",T*32*T,{&norm,&ex,&T});run("vit_attention_inverse_fast",T*32*16,{&ex,&inv,&T});run("vit_attention_av_fast",T*C,{&norm,&ex,&inv,&av,&T});check("attention",av,ar);}

 {NativeVitLinear stage;stage.Create(d,di,di,T,C,C,false,pw,dir);linear(stage);auto b=readback(stage.Output());std::vector<float>r(T*C);if(b.size()!=r.size()*4)throw std::runtime_error("projection size");memcpy(r.data(),b.data(),b.size());run("vit_project",T*C,{&hi,&hp,&hi,&proj,&T,&C,&C});check("projection",proj,r);}
 if(T==64){unsigned iclist[]={1024,512,256,128,64};const wchar_t*files[]={L"decoder39-weights.f32",L"block48-weights.f32",L"block56-weights.f32",L"block62-weights.f32",L"block66-weights.f32"};for(unsigned z=0;z<5;z++){unsigned ic=iclist[z],oc=ic/2,iw=8,ih=8,ow=16,oh=16;auto wd=load(files[z]);void*hwd=hu(wd);std::vector<float>skip(T*4*oc);for(size_t i=0;i<skip.size();i++)skip[i]=input[(i*13)%input.size()];auto*ds=upload(skip);void*hs=hu(skip),*ho=alloc(skip.size());NativeVitLinear stage;stage.Create(d,di,ds,T,ic,oc,false,wd,dir,true);linear(stage);auto b=readback(stage.Output());std::vector<float>r(skip.size());if(b.size()!=r.size()*4)throw std::runtime_error("decoder validation expects f32 fixture output");memcpy(r.data(),b.data(),b.size());run("decoder_project2x",T*oc,{&hi,&hwd,&hs,&ho,&iw,&ih,&ow,&oh,&ic,&oc});std::string name="decoder"+std::to_string(ic);check(name.c_str(),ho,r);ds->Release();}}
 if(argc==7){if(T!=64)throw std::runtime_error("split oracle fixture requires64 tokens");auto fw=load(L"block23-ffwd.f32");std::vector<float>packed(fw.size()/2);auto*ph=reinterpret_cast<unsigned short*>(packed.data());for(size_t i=0;i<fw.size();i++){unsigned bits;memcpy(&bits,&fw[i],4);unsigned mag=bits&0x7fffffffu;ph[i]=static_cast<unsigned short>(((bits>>16)&0x8000u)|(mag?((mag>>13)-0x1c000u):0));}auto*dw=upload(packed),*output=buffer(d,T*512*4,D3D12_HEAP_TYPE_DEFAULT);D3D12_ROOT_PARAMETER pp[4]{};pp[0].ParameterType=pp[1].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;pp[1].Descriptor.ShaderRegister=1;pp[2].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;pp[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;pp[3].Constants={0,0,2};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=4;rd.pParameters=pp;ID3DBlob*blob=nullptr,*err=nullptr;ck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&err));ID3D12RootSignature*root=nullptr;ck(d->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),IID_PPV_ARGS(&root)));blob->Release();if(err)err->Release();ck(D3DReadFileToBlob(wide(argv[6]).c_str(),&blob));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));blob->Release();submit.Submit([&](ID3D12GraphicsCommandList*c){transition(c,output,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);c->SetComputeRootSignature(root);c->SetPipelineState(pso);c->SetComputeRootShaderResourceView(0,di->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,dw->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(2,output->GetGPUVirtualAddress());unsigned dims[]={8,8};c->SetComputeRoot32BitConstants(3,2,dims,0);c->Dispatch(T/16,8,1);transition(c,output,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();auto raw=readback(output);std::vector<float>r(T*512);memcpy(r.data(),raw.data(),r.size()*4);void*hw=hu(fw),*mix=alloc(T*512),*sh=alloc(T*2048),*so=alloc(T*512);run("split_mix",T*512,{&hi,&hw,&mix,&T});run("split_expand",T*2048,{&mix,&hw,&sh,&T});run("split_contract",T*512,{&sh,&hw,&so,&T});check("split-ffwd",so,r);pso->Release();root->Release();output->Release();dw->Release();}
 // Stream0f uses the shipped production PSO, tiled E4M3 input/weights/output and raster f32 residual.
 {auto sw=load(L"block23-ffwd-projection.f32");auto encode=[&](float v){for(unsigned b=0;b<256;b++)if((b&127)<127&&fp8(b)==v)return static_cast<unsigned char>(b);throw std::runtime_error("stream0 non-FP8 matrix/input value");};std::vector<float>ib(T*512/4),wb((262144+2048)/4);auto*ip=reinterpret_cast<unsigned char*>(ib.data()),*wp=reinterpret_cast<unsigned char*>(wb.data());for(unsigned t=0;t<T;t++)for(unsigned c=0;c<512;c++)ip[((t/16)*16+c/32)*512+(t%16)*32+c%32]=encode(input[t*512+c]);for(unsigned row=0;row<512;row++)for(unsigned k=0;k<512;k++)wp[((row/16)*16+k/32)*512+(k%32)*16+row%16]=encode(sw[row*512+k]);memcpy(wp+262144,sw.data()+262144,2048);auto*pi=upload(ib),*pw=upload(wb),*po=buffer(d,T*512,D3D12_HEAP_TYPE_DEFAULT);D3D12_ROOT_PARAMETER pp[5]{};for(unsigned k=0;k<3;k++){pp[k].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;pp[k].Descriptor.ShaderRegister=k;}pp[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;pp[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;pp[4].Constants={0,0,6};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=5;rd.pParameters=pp;ID3DBlob*blob=nullptr,*err=nullptr;ck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&err));ID3D12RootSignature*root=nullptr;ck(d->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),IID_PPV_ARGS(&root)));blob->Release();if(err)err->Release();ck(D3DReadFileToBlob((dir+L"\\native_wave_project_stream0f_c512.cso").c_str(),&blob));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));blob->Release();submit.Submit([&](ID3D12GraphicsCommandList*c){transition(c,po,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);c->SetComputeRootSignature(root);c->SetPipelineState(pso);c->SetComputeRootShaderResourceView(0,pi->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,pw->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(2,di->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(3,po->GetGPUVirtualAddress());unsigned dims[]={8,T/8,8,T/8,0,0};c->SetComputeRoot32BitConstants(4,6,dims,0);c->Dispatch(T/16,8,1);transition(c,po,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();auto raw=readback(po);std::vector<float>r(T*512);for(unsigned t=0;t<T;t++)for(unsigned c=0;c<512;c++)r[t*512+c]=fp8(raw[((t/16)*16+c/32)*512+(t%16)*32+c%32]);void*hw=hu(sw),*ho=alloc(T*512);run("split_projection",T*512,{&hi,&hw,&hi,&ho,&T});check("split-projection-stream0f",ho,r);pso->Release();root->Release();po->Release();pw->Release();pi->Release();}
 di->Release();fflush(stdout);
 }
 for(void*p:allocs)hip.Check(hip.hipFree(p),"free");hip.Check(hip.hipModuleUnload(module),"unload");q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",total,bad);return bad?1:total?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
