#pragma once
// SDKless HIP host graph. Scalar numerical validation path, not a realtime backend.
#include "hip_api.h"
#include <cstdint>
#include <cstring>
#include <fstream>
#include <vector>
#include <map>
#include <memory>
#include <limits>
#include <utility>
#include <functional>
#include <set>
namespace hip_reference {
using U=uint32_t;using Api=hip_probe::Api;using Handle=hip_probe::Handle;
inline float Half(uint16_t h){U s=U(h&0x8000u)<<16,e=(h>>10)&31u,m=h&1023u,b;if(!e){if(!m)b=s;else{int sh=0;while(!(m&1024)){m<<=1;sh++;}b=s|(U(113-sh)<<23)|((m&1023)<<13);}}else b=s|((e==31?255:e+112)<<23)|(m<<13);float f;std::memcpy(&f,&b,4);return f;}
inline std::vector<char> ReadBytes(const std::string&path){std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("missing "+path);auto n=f.tellg();if(n<=0)throw std::runtime_error("empty "+path);std::vector<char>b(static_cast<size_t>(n));f.seekg(0);if(!f.read(b.data(),n))throw std::runtime_error("read "+path);return b;}
inline std::vector<float> ReadWeights(const std::string&path){std::ifstream test(path,std::ios::binary);bool full=bool(test);test.close();auto b=ReadBytes(full?path:path.substr(0,path.size()-4)+".f16");if(b.size()%(full?4:2))throw std::runtime_error("weight size "+path);std::vector<float>v(b.size()/(full?4:2));if(full)std::memcpy(v.data(),b.data(),b.size());else for(size_t i=0;i<v.size();i++){uint16_t h;std::memcpy(&h,b.data()+i*2,2);v[i]=Half(h);}return v;}
struct Allocation {Api*api;void*ptr{};size_t bytes;Allocation(Api&a,size_t n):api(&a),bytes(n){if(!n)throw std::runtime_error("zero HIP allocation");a.Check(a.hipMalloc(&ptr,n),"hipMalloc");}~Allocation(){if(ptr){api->hipDeviceSynchronize();api->hipFree(ptr);}}};
using Tensor=std::shared_ptr<Allocation>;
struct Options {U width=512,height=512,seed=0,post_shift=0;std::string assets,modules,dump_dir;unsigned runtime=7;bool fast_vit=false,wmma=false;};
class Network {
 Api api;Handle stream{};std::map<std::string,Handle>modules,functions;std::map<std::string,Tensor>weights;Options opt;
 U W,H;std::function<void(const std::string&)>progress;
 static U Count(size_t n){if(!n||n>std::numeric_limits<U>::max())throw std::runtime_error("HIP reference index count overflow");return U(n);}
 Tensor New(size_t n){Count(n);return std::make_shared<Allocation>(api,n*4);}
 Tensor Upload(const void*p,size_t bytes){if(!bytes||bytes%4)throw std::runtime_error("upload size");auto t=New(bytes/4);api.Check(api.hipMemcpy(t->ptr,p,bytes,1),"upload");return t;}
 void* P(const Tensor&t){return t?t->ptr:nullptr;}
 static size_t WeightElements(const std::string&name){
  if(name=="head-matrix.f32")return 524288;
  if(name=="decoder39-weights.f32")return 524800;
  if(name=="post70-scales.f32")return 64;
  if(name=="post70-head.f32")return 96;
  U b=70;std::string type;
  if(name.rfind("block",0)==0){auto dash=name.find('-');if(dash==std::string::npos)throw std::runtime_error("weight name");b=U(std::stoul(name.substr(5,dash-5)));type=name.substr(dash+1);}else if(name.rfind("post70-",0)==0)type=name.substr(7);else throw std::runtime_error("unknown weight "+name);
  U c=b<=4?32:b<=8?64:b<=14?128:b<=22?256:b<=30?512:b<=38?1024:b<=47?512:b<=55?256:b<=61?128:b<=65?64:32;
  if(type=="ds.f32")return size_t(2)*c*c;
  if(type=="weights.f32")return size_t(2)*c*c+c;
  if(type=="ffwd.f32")return 524288;
  if(type=="ffwd-projection.f32")return 262656;
  if(type=="ffn.f32")return c==32?8736:size_t(9)*c*c+c;
  if(type=="attention.f32")return c==32?8225:size_t(4)*c*c+(c/32)*4096+c/32+c;
  if(type=="expand.f32")return 4194304;
  if(type=="contract.f32")return 4195328;
  if(type=="qkv.f32")return 3145760;
  if(type=="projection.f32")return 1049600;
  throw std::runtime_error("unknown weight suffix "+name);
 }
 void* Weight(const std::string&name){auto it=weights.find(name);if(it==weights.end()){auto v=ReadWeights(opt.assets+"/"+name);if(v.size()!=WeightElements(name))throw std::runtime_error("weight shape "+name+": "+std::to_string(v.size()));it=weights.emplace(name,Upload(v.data(),v.size()*4)).first;}return P(it->second);}
 Handle Fn(const std::string&m,const std::string&name){std::string key=m+":"+name;auto it=functions.find(key);if(it!=functions.end())return it->second;Handle f{};api.Check(api.hipModuleGetFunction(&f,modules.at(m),name.c_str()),name.c_str());functions.emplace(key,f);return f;}
 template<class...A>void Run(const char*m,const char*name,size_t n,A...args){
  U count=Count(n),threads=256;std::string module=m,kernel=name;
  static const std::set<std::string> accelerated={"c32_ffn_expand","c32_ffn_contract","c32_attn_qkv","c32_attn_scores","c32_attn_av","c32_attn_project","mh_ffn_expand","mh_ffn_contract","mh_ffn_project","mh_qkv","mh_scores_exp","mh_attention_av","mh_attention_project","mh_pool_project","split_mix","split_expand","split_contract","split_projection","vit_expand","vit_project","vit_qkv_project","decoder_project2x"};
  if(opt.wmma&&accelerated.count(kernel)){if(count%256)throw std::runtime_error("WMMA tile count: "+kernel);module+="_wmma";if(module!="deep_wmma")kernel+="_wmma";threads=32;}
  void*argv[]={static_cast<void*>(&args)...};api.Check(api.hipModuleLaunchKernel(Fn(module,kernel),(count+255ull)/256,1,1,threads,1,1,0,stream,argv,nullptr),name);api.Check(api.hipStreamSynchronize(stream),name);
 }
 void Stage(const std::string&name,const Tensor&t){if(progress)progress(name);if(opt.dump_dir.empty())return;std::vector<char>b(t->bytes);api.Check(api.hipMemcpy(b.data(),P(t),b.size(),2),"stage dump");std::ofstream f(opt.dump_dir+"/"+name+".f32",std::ios::binary);if(!f.write(b.data(),b.size()))throw std::runtime_error("stage dump write");}
 static std::string Block(U b,const char*s){return "block"+std::to_string(b)+"-"+s+".f32";}
 struct C32Result{Tensor main,down,raw;U workw,workh,sx,sy;};
 C32Result C32Body(Tensor input,U w,U h,const std::string&fw,const std::string&aw){U n=w*h,windows=n/64;auto hidden=New(size_t(n)*128),ffn=New(size_t(n)*32);Run("c32","c32_ffn_expand",size_t(n)*128,P(input),Weight(fw),P(hidden),n);Run("c32","c32_ffn_contract",size_t(n)*32,P(input),P(hidden),Weight(fw),P(ffn),n,U(1));hidden.reset();auto qkv=New(size_t(n)*96),norm=New(size_t(n)*64);Run("c32","c32_attn_qkv",size_t(n)*96,P(ffn),Weight(aw),P(qkv),n);Run("c32","c32_attn_normalize",n,P(qkv),Weight(aw),P(norm),n);auto ex=New(size_t(windows)*4096),prob=New(size_t(windows)*4096);Run("c32","c32_attn_scores",size_t(windows)*4096,P(norm),Weight(aw),P(ex),windows);norm.reset();Run("c32","c32_attn_probabilities",size_t(n),P(ex),P(prob),windows);ex.reset();auto av=New(size_t(n)*32);Run("c32","c32_attn_av",size_t(n)*32,P(prob),P(qkv),P(av),windows);prob.reset();qkv.reset();auto raw=New(size_t(n)*32);Run("c32","c32_attn_project",size_t(n)*32,P(ffn),P(av),Weight(aw),P(raw),n,U(1));ffn.reset();av.reset();auto main=New(size_t(n)*32),down=New(size_t(n/4)*32);Run("c32","c32_finish",size_t(n)*32,P(raw),P(main),P(down),w,h);return {main,down,raw,w,h,0,0};}
 C32Result C32(Tensor input,U w,U h,U shift,const std::string&fw,const std::string&aw){U sx=(shift&1)?4:0,sy=(shift&2)?4:0,ww=w+2*sx,hh=h+2*sy;auto packed=New(size_t(ww)*hh*32);Run("boundary","hip_c32_pack",size_t(ww)*hh*32,P(input),P(packed),w,h,ww,hh,sx,sy);auto result=C32Body(packed,ww,hh,fw,aw);auto cropped=New(size_t(w)*h*32);Run("mh","mh_shift_crop",size_t(w)*h*32,P(result.main),P(cropped),w,h,ww,sx,sy,U(32));result.main=cropped;result.sx=sx;result.sy=sy;return result;}
 Tensor Attention(Tensor input,U w,U h,U c,const std::string&aw,bool raw){U n=w*h,windows=n/64,heads=c/32;auto qkv=New(size_t(n)*3*c),qk=New(size_t(n)*2*c);Run("mh","mh_qkv",size_t(n)*3*c,P(input),Weight(aw),P(qkv),n,c);Run("mh","mh_normalize",size_t(n)*heads,P(qkv),Weight(aw),P(qk),n,c);auto ex=New(size_t(windows)*heads*4096),prob=New(size_t(windows)*heads*4096);Run("mh","mh_scores_exp",size_t(windows)*heads*4096,P(qk),Weight(aw),P(ex),w,h,c);qk.reset();Run("mh","mh_probabilities",size_t(windows)*heads*64,P(ex),P(prob),windows,c);ex.reset();auto av=New(size_t(n)*c);Run("mh","mh_attention_av",size_t(n)*c,P(prob),P(qkv),P(av),w,h,c);prob.reset();qkv.reset();auto out=New(size_t(n)*c);Run("mh","mh_attention_project",size_t(n)*c,P(av),P(input),Weight(aw),P(out),n,c,U(raw));return out;}
 Tensor Body(Tensor input,U w,U h,U c,U shift,U block,bool raw){U sx=(shift&1)?4:0,sy=(shift&2)?4:0,ww=(w+sx+7)&~7u,hh=(h+sy+7)&~7u,n=ww*hh;auto packed=New(size_t(n)*c);Run("mh","mh_shift_pack",size_t(n)*c,P(input),P(packed),w,h,ww,hh,sx,sy,c,U(0));Tensor ffn=New(size_t(n)*c);
 if(c==512){auto mixed=New(size_t(n)*512),hidden=New(size_t(n)*2048),contract=New(size_t(n)*512);auto fw=Weight(Block(block,"ffwd"));Run("deep","split_mix",size_t(n)*512,P(packed),fw,P(mixed),n);Run("deep","split_expand",size_t(n)*2048,P(mixed),fw,P(hidden),n);mixed.reset();Run("deep","split_contract",size_t(n)*512,P(hidden),fw,P(contract),n);hidden.reset();Run("deep","split_projection",size_t(n)*512,P(contract),Weight(Block(block,"ffwd-projection")),P(packed),P(ffn),n);}
 else{auto hidden=New(size_t(n)*c*4),middle=New(size_t(n)*c);auto fw=Weight(Block(block,"ffn"));Run("mh","mh_ffn_expand",size_t(n)*c*4,P(packed),fw,P(hidden),n,c);Run("mh","mh_ffn_contract",size_t(n)*c,P(hidden),fw,P(middle),n,c);hidden.reset();Run("mh","mh_ffn_project",size_t(n)*c,P(middle),P(packed),fw,P(ffn),n,c);}packed.reset();auto attended=Attention(ffn,ww,hh,c,Block(block,"attention"),raw);auto out=New(size_t(w)*h*c);Run("mh","mh_shift_crop",size_t(w)*h*c,P(attended),P(out),w,h,ww,sx,sy,c);Stage("block"+std::to_string(block),out);return out;}
 Tensor Down(Tensor raw,U w,U h,U c,const std::string&file,bool head=false){U ow=w/2,oh=h/2,vw=0,vh=0;if(head&&w==60&&h==36){ow=32;oh=20;vw=30;vh=18;}auto pooled=New(size_t(ow)*oh*c),out=New(size_t(ow)*oh*c*2);Run("mh","mh_pool",size_t(ow)*oh*c,P(raw),P(pooled),ow,oh,w,vw,vh,c);Run("mh","mh_pool_project",size_t(ow)*oh*c*2,P(pooled),Weight(file),P(out),ow,oh,vw,vh,c);return out;}
 Tensor Gather(Tensor input,U n,bool inverse){std::vector<U>map(size_t(n)*1024);for(U t=0;t<n;t++)for(U c=0;c<1024;c++){U raster=(t&~15u)|((t&1u)<<3)|((t&14u)>>1),ch=(c&~31u)|((c&1u)<<1)|((c&2u)>>1)|((c&4u)<<2)|((c&24u)>>1),to=t*1024+c,from=raster*1024+ch;if(inverse)map[from]=to;else map[to]=from;}auto indices=Upload(map.data(),map.size()*4),out=New(map.size());Run("deep","vit_gather",map.size(),P(input),P(indices),P(out),Count(map.size()));return out;}
 Tensor Vit(Tensor input,U n,U block){auto hidden=New(size_t(n)*4096),contract=New(size_t(n)*1024);Run("deep","vit_expand",size_t(n)*4096,P(input),Weight(Block(block,"expand")),P(hidden),n,U(1024),U(4096));Run("deep","vit_project",size_t(n)*1024,P(hidden),Weight(Block(block,"contract")),P(input),P(contract),n,U(4096),U(1024));hidden.reset();auto qkv=New(size_t(n)*3072),norm=New(size_t(n)*3072);auto qw=Weight(Block(block,"qkv"));Run("deep","vit_qkv_project",size_t(n)*3072,P(contract),qw,P(qkv),n);Run("deep","vit_qkv_normalize",size_t(n)*96,P(qkv),qw,P(norm),n);qkv.reset();auto ex=New(size_t(n)*32*n),inv=New(size_t(n)*32),av=New(size_t(n)*1024);Run("deep",opt.fast_vit?"vit_attention_scores_fast":"vit_attention_scores",size_t(n)*32*n,P(norm),P(ex),n);Run("deep",opt.fast_vit?"vit_attention_inverse_fast":"vit_attention_inverse",size_t(n)*32,P(ex),P(inv),n);Run("deep",opt.fast_vit?"vit_attention_av_fast":"vit_attention_av",size_t(n)*1024,P(norm),P(ex),P(inv),P(av),n);norm.reset();ex.reset();inv.reset();auto out=New(size_t(n)*1024);Run("deep","vit_project",size_t(n)*1024,P(av),Weight(Block(block,"projection")),P(contract),P(out),n,U(1024),U(1024));Stage("block"+std::to_string(block),out);return out;}
 Tensor Up(Tensor input,Tensor skip,U iw,U ih,U ow,U oh,U ic,U oc,const std::string&file){auto out=New(size_t(ow)*oh*oc);Run("deep","decoder_project2x",size_t(iw)*ih*oc,P(input),Weight(file),P(skip),P(out),iw,ih,ow,oh,ic,oc);return out;}
 static U Shift(U block){static constexpr U s[]={0,3,1,2,0,3,1,2,0,3,1,2,0,3,1,2,1,2,0,3,1,2,0,3,1,2,0,3,1,2};if(block<40||block>69)throw std::runtime_error("decoder shift");return s[block-40];}
public:
 explicit Network(Options o):api(o.runtime),opt(std::move(o)),W(opt.width),H(opt.height){if(opt.post_shift>3)throw std::runtime_error("post shift must be 0..3");if(!((W==512&&H==512)||(W==1920&&H==1152)))throw std::runtime_error("reference geometry: 512x512 or 1920x1152 only");api.Check(api.hipInit(0),"hipInit");api.Check(api.hipSetDevice(0),"device");api.Check(api.hipStreamCreate(&stream),"stream");try{const char*names[][2]={{"c32","c32_prefix_reference.hsaco"},{"mh","multihead-reference.hsaco"},{"deep","deep_reference.hsaco"},{"boundary","boundary_reference.hsaco"}};for(auto&v:names){Handle m{};api.Check(api.hipModuleLoad(&m,(opt.modules+"/"+v[1]).c_str()),v[1]);modules[v[0]]=m;}if(opt.wmma){const char*wm[][2]={{"c32_wmma","c32_wmma.hsaco"},{"mh_wmma","multihead-wmma.hsaco"},{"deep_wmma","deep_wmma.hsaco"}};for(auto&v:wm){Handle m{};api.Check(api.hipModuleLoad(&m,(opt.modules+"/"+v[1]).c_str()),v[1]);modules[v[0]]=m;}}}catch(...){for(auto&m:modules)api.hipModuleUnload(m.second);api.hipStreamDestroy(stream);throw;}}
 ~Network(){api.hipStreamSynchronize(stream);weights.clear();for(auto&m:modules)api.hipModuleUnload(m.second);api.hipStreamDestroy(stream);}
 void SetProgress(std::function<void(const std::string&)>f){progress=std::move(f);}
 std::vector<float> Infer(const std::vector<float>&rgba,const std::vector<float>&noise,const std::vector<float>*history=nullptr){if(rgba.size()!=size_t(W)*H*4||noise.size()!=50331648||(history&&history->size()!=rgba.size()))throw std::runtime_error("network input sizes");auto color=Upload(rgba.data(),rgba.size()*4),noisegpu=Upload(noise.data(),noise.size()*4),hist=history?Upload(history->data(),history->size()*4):Tensor{};auto tiles=New(rgba.size()),base=New(rgba.size()),prefix=New(size_t(W)*H*32);Run("boundary","hip_input_reflect",size_t(W)*H,P(color),P(base),P(tiles),W,H,W,H);color=base;Run("c32","dlss5_prefix_reference",size_t(W)*H,P(tiles),P(hist),P(noisegpu),Weight("block0-ffn.f32"),P(prefix),static_cast<void*>(nullptr),W,H,opt.seed,U(history!=nullptr));tiles.reset();noisegpu.reset();hist.reset();auto pre=C32Body(prefix,W,H,"block0-ffn.f32","block0-attention.f32");prefix.reset();pre.raw.reset();Tensor skip0=pre.main,source=pre.down;pre.main.reset();pre.down.reset();Stage("block0",skip0);Tensor skips[5];U shifts[]={0,3,1,2,0,3,1,2};C32Result last;
 for(U b=1;b<=4;b++){last=C32(source,W/2,H/2,shifts[b-1],Block(b,"ffn"),Block(b,"attention"));source=last.main;Stage("block"+std::to_string(b),source);}skips[0]=source;auto poolcrop=New(size_t(W/4)*(H/4)*32);Run("mh","mh_shift_crop",size_t(W/4)*(H/4)*32,P(last.down),P(poolcrop),W/4,H/4,last.workw/2,last.sx/2,last.sy/2,U(32));source=New(size_t(W/4)*(H/4)*64);Run("mh","mh_pool_project",size_t(W/4)*(H/4)*64,P(poolcrop),Weight("block4-ds.f32"),P(source),W/4,H/4,U(0),U(0),U(32));poolcrop.reset();last={};
 U starts[]={5,9,15},counts[]={4,6,8},channels[]={64,128,256};for(U g=0;g<3;g++){U w=W/(4u<<g),h=H/(4u<<g);for(U j=0;j<counts[g];j++)source=Body(source,w,h,channels[g],shifts[j],starts[g]+j,j+1==counts[g]);skips[g+1]=source;source=Down(source,w,h,channels[g],Block(starts[g]+counts[g]-1,"ds"));}
 for(U j=0;j<8;j++){source=Body(source,W/32,H/32,512,shifts[j],23+j,j==7);}skips[4]=source;source=Down(source,W/32,H/32,512,"head-matrix.f32",true);U vw=W==1920?32:8,vh=W==1920?20:8,n=vw*vh;Stage("head",source);source=Gather(source,n,false);for(U b=31;b<=38;b++)source=Vit(source,n,b);source=Gather(source,n,true);source=Up(source,skips[4],vw,vh,W/32,H/32,1024,512,"decoder39-weights.f32");skips[4].reset();Stage("block39",source);for(U b=40;b<=47;b++)source=Body(source,W/32,H/32,512,Shift(b),b,false);
 U ups[]={48,56,62},cs[]={256,128,64},ends[]={55,61,65};for(U g=0;g<3;g++){U ow=W/(16u>>g),oh=H/(16u>>g);source=Up(source,skips[3-g],ow/2,oh/2,ow,oh,cs[g]*2,cs[g],Block(ups[g],"weights"));skips[3-g].reset();for(U b=ups[g];b<=ends[g];b++)source=Body(source,ow,oh,cs[g],Shift(b),b,false);}source=Up(source,skips[0],W/4,H/4,W/2,H/2,64,32,"block66-weights.f32");skips[0].reset();for(U b=66;b<=69;b++){auto r=C32(source,W/2,H/2,Shift(b),Block(b,"ffn"),Block(b,"attention"));source=r.main;Stage("block"+std::to_string(b),source);}
 auto merged=New(size_t(W)*H*32);Run("boundary","hip_post_merge",size_t(W)*H*32,P(source),P(skip0),Weight("post70-scales.f32"),P(merged),W,H);source.reset();skip0.reset();auto post=C32(merged,W,H,opt.post_shift,"post70-ffn.f32","post70-attention.f32");merged.reset();auto out=New(size_t(W)*H*3);Run("boundary","hip_post_head_exact",size_t(W)*H*3,P(post.raw),P(color),Weight("post70-head.f32"),P(out),W,H,post.workw,post.sx,post.sy,.03125f);Stage("block70",out);std::vector<float>result(size_t(W)*H*3);api.Check(api.hipMemcpy(result.data(),P(out),result.size()*4,2),"final readback");return result;}
};
}
