// Offline D3D12 production 900p oracle for the HIP full-processing-grid fixture.
// No game hook, texture codec, motion/history, installed flags writes, or DLL deployment.
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <dxgi1_6.h>
#include <cstdio>
#include <cmath>
#include <cctype>
#include <fstream>
#include <vector>
#include <string>
#include "native_actual_network70.h"
#include "native_game_submission.h"
extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static void environment(const std::string&k,const std::string&v){if(_putenv_s(k.c_str(),v.c_str()))throw std::runtime_error("environment");std::wstring wk(k.begin(),k.end()),wv(v.begin(),v.end());if(_wputenv_s(wk.c_str(),wv.c_str()))throw std::runtime_error("wide environment");}
static void flags(const wchar_t*path){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){auto*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)environment(std::string(n.begin(),n.end()),"");std::ifstream f(path);if(!f)throw std::runtime_error("flags missing");std::string s;while(std::getline(f,s)){auto p=s.find_first_not_of(" \t\r");if(p==std::string::npos||s[p]=='#'||s[p]==';')continue;s=s.substr(p);auto eq=s.find('=');if(eq==std::string::npos)continue;auto key=s.substr(0,eq),v=s.substr(eq+1);while(!key.empty()&&isspace((unsigned char)key.back()))key.pop_back();while(!v.empty()&&isspace((unsigned char)v.back()))v.pop_back();p=v.find_first_not_of(" \t");v=p==std::string::npos?"":v.substr(p);if(key.rfind("DLSS5_",0)==0)environment(key,v);}}
static ID3D12Resource*buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE type){D3D12_HEAP_PROPERTIES hp{};hp.Type=type;D3D12_RESOURCE_DESC rd{};rd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;rd.Width=bytes;rd.Height=1;rd.DepthOrArraySize=rd.MipLevels=1;rd.SampleDesc.Count=1;rd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&rd,type==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void barrier(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER x{};x.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;x.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&x);}
int wmain(int argc,wchar_t**argv){try{
 if(argc!=5&&argc!=6){fprintf(stderr,"Usage: hlsl_network_oracle.exe ASSETS FLAGS INPUT_PROCESSING_RGBA_F32 OUTPUT_PROCESSING_RGB_F32 [STAGE_DUMP_PREFIX]\n900p fixed: input 1600x1024 RGBA, output 1600x1024 RGB; seed=0 post_shift=3 history=off.\n");return 2;}
 constexpr UINT W=1600,H=1024;constexpr size_t pixels=size_t(W)*H;flags(argv[2]);environment("DLSS5_NETWORK_HEIGHT","900");environment("DLSS5_NETWORK_720P","0");environment("DLSS5_DEBUG_DUMPS","");environment("DLSS5_BLACK_PROBE","0");environment("DLSS5_GAME_PROBE","0");environment("DLSS5_SHOW_FPS","0");environment("DLSS5_OVERLAP","0");environment("DLSS5_TEST_ISOLATE","");
 // Empty isolate must be absent: this process-local name is unrelated to packaged flags.
 _putenv_s("DLSS5_TEST_ISOLATE","");_wputenv_s(L"DLSS5_TEST_ISOLATE",L"");
 std::ifstream in(argv[3],std::ios::binary|std::ios::ate);if(!in||in.tellg()!=std::streamoff(pixels*16))throw std::runtime_error("input must be exactly 1600x1024 RGBA f32");std::vector<float>rgba(pixels*4),tiles(pixels*4);in.seekg(0);if(!in.read(reinterpret_cast<char*>(rgba.data()),rgba.size()*4))throw std::runtime_error("input read");for(float x:rgba)if(!std::isfinite(x))throw std::runtime_error("nonfinite input");for(UINT y=0;y<H;y++)for(UINT x=0;x<W;x++){size_t p=size_t(y)*W+x,t=((size_t(y/8)*(W/8)+x/8)*64+(y%8)*8+x%8);std::memcpy(&tiles[t*4],&rgba[p*4],16);}
 const IID experimental={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&experimental,nullptr,nullptr));IDXGIFactory6*factory=nullptr;ck(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)));ID3D12Device*d=nullptr;for(UINT i=0;;i++){IDXGIAdapter1*a=nullptr;if(factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&a))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 info{};a->GetDesc1(&info);if(info.VendorId==0x1002){ck(D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));wprintf(L"adapter=%ls\n",info.Description);}a->Release();if(d)break;}factory->Release();if(!d)throw std::runtime_error("AMD D3D12 adapter missing");
 ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q,false);
 auto upload=[&](const std::vector<float>&values){auto*u=buffer(d,values.size()*4,D3D12_HEAP_TYPE_UPLOAD),*r=buffer(d,values.size()*4,D3D12_HEAP_TYPE_DEFAULT);void*p=nullptr;D3D12_RANGE none{};ck(u->Map(0,&none,&p));std::memcpy(p,values.data(),values.size()*4);u->Unmap(0,nullptr);submit.Submit([&](ID3D12GraphicsCommandList*c){c->CopyBufferRegion(r,0,u,0,values.size()*4);barrier(c,r,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();u->Release();return r;};auto*rgb=upload(rgba),*tiled=upload(tiles);rgba.clear();tiles.clear();std::wstring assets=argv[1];auto noise=NativeReadF32(assets+L"\\noise.f32","oracle noise");
 {NativeActualNetwork70 network;// Production prefix PSO declares t3 even when temporal_enabled=0. Bind
 // the base buffer to retain the same root-signature contract as NativeGameFrame;
 // Run(false) keeps history sampling disabled. No synthetic history is consumed.
 network.Create(d,tiled,rgb,noise,assets,rgb,3);noise.clear();noise.shrink_to_fit();printf("oracle run processing=1600x1024 seed=0 post_shift=3 history=off\n");fflush(stdout);network.Run(submit,0,false);submit.Flush();
 if(argc==6){auto dump=[&](const wchar_t*name,ID3D12Resource*r){if(!r){wprintf(L"dump absent %ls\n",name);return;}size_t n=size_t(r->GetDesc().Width);auto*readback=buffer(d,n,D3D12_HEAP_TYPE_READBACK);submit.Submit([&](ID3D12GraphicsCommandList*c){barrier(c,r,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(readback,0,r,0,n);barrier(c,r,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();void*p=nullptr;D3D12_RANGE rr{0,n};ck(readback->Map(0,&rr,&p));std::wstring path=std::wstring(argv[5])+L"-"+name+L".bin";std::ofstream f(path.c_str(),std::ios::binary);if(!f.write(static_cast<const char*>(p),n))throw std::runtime_error("stage dump write");readback->Unmap(0,nullptr);readback->Release();wprintf(L"dump %ls bytes=%llu\n",name,(unsigned long long)n);};
  dump(L"pre-main8",network.PreMain8());dump(L"pre-down",network.PreDown());dump(L"block4-main8",network.Block4Main8());if(!network.Block4Main8())dump(L"block4-main-work",network.Block4Main());dump(L"block4-down",network.Block4Down());dump(L"head",network.Head());dump(L"project66",network.Project66Output());dump(L"block69-main8",network.Block69Main8());dump(L"block69-down",network.Block69Down());
 }
 auto*output=network.Output();size_t bytes=pixels*3*4;if(output->GetDesc().Width<bytes)throw std::runtime_error("oracle output capacity");auto*rb=buffer(d,bytes,D3D12_HEAP_TYPE_READBACK);submit.Submit([&](ID3D12GraphicsCommandList*c){barrier(c,output,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,output,0,bytes);barrier(c,output,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});submit.Flush();void*p=nullptr;D3D12_RANGE range{0,bytes};ck(rb->Map(0,&range,&p));auto*v=static_cast<const float*>(p);size_t bad=0;double sum=0;float lo=v[0],hi=v[0];for(size_t i=0;i<pixels*3;i++){if(!std::isfinite(v[i]))bad++;else{sum+=v[i];lo=std::min(lo,v[i]);hi=std::max(hi,v[i]);}}std::ofstream out(argv[4],std::ios::binary);if(!out.write(static_cast<const char*>(p),bytes))throw std::runtime_error("oracle output write");rb->Unmap(0,nullptr);rb->Release();printf("RESULT count=%zu invalid=%zu min=%.9g max=%.9g mean=%.9g\n",pixels*3,bad,lo,hi,sum/(pixels*3));if(bad)throw std::runtime_error("nonfinite oracle output");}
 submit.Flush();tiled->Release();rgb->Release();q->Release();d->Release();return 0;
 }catch(const std::exception&e){fprintf(stderr,"oracle FAILED: %s\n",e.what());return 1;}}
