// Shared-buffer and D3D12-fence round trip. Does not use Agility preview or experimental shader features.
#define WIN32_LEAN_AND_MEAN
#include "hip_api.h"
#include <d3d12.h>
#include <dxgi1_6.h>
#include <vector>
#include <cstring>
using namespace hip_probe;
static void ck(HRESULT h,const char*s){if(FAILED(h))throw std::runtime_error(std::string(s)+" hr="+std::to_string(unsigned(h)));}
int main(int argc,char**argv){try{
 const unsigned runtime=argc>1?unsigned(std::stoul(argv[1])):7;const int type=argc>2?std::stoi(argv[2]):5;const unsigned dedicated=argc>3?unsigned(std::stoul(argv[3])):1;
 Api hip(runtime);hip.Check(hip.hipInit(0),"hipInit");int count=0,version=0;hip.Check(hip.hipGetDeviceCount(&count),"count");hip.Check(hip.hipRuntimeGetVersion(&version),"version");printf("HIP runtime=%d devices=%d memory_type=%d flags=%u\n",version,count,type,dedicated);fflush(stdout);
 IDXGIFactory4*factory=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&factory)),"factory");IDXGIAdapter1*adapter=nullptr;int ordinal=-1;
 for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(factory->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002){char dn[256]{};WideCharToMultiByte(CP_UTF8,0,desc.Description,-1,dn,256,nullptr,nullptr);for(int n=0;n<count;n++){char hn[256]{};hip.Check(hip.hipDeviceGetName(hn,256,n),"name");if(!strcmp(dn,hn)){adapter=a;ordinal=n;printf("adapter=%s HIP ordinal=%d LUID=%08x:%08x\n",dn,n,unsigned(desc.AdapterLuid.HighPart),desc.AdapterLuid.LowPart);break;}}}if(adapter)break;a->Release();}
 if(!adapter)throw std::runtime_error("no matching DXGI/HIP AMD adapter");hip.Check(hip.hipSetDevice(ordinal),"set device");
 ID3D12Device*d=nullptr;ck(D3D12CreateDevice(adapter,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)),"device");
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)),"queue");ID3D12CommandAllocator*alloc=nullptr;ID3D12GraphicsCommandList*c=nullptr;ck(d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&alloc)),"allocator");ck(d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,alloc,nullptr,IID_PPV_ARGS(&c)),"list");
 constexpr UINT64 bytes=4096;D3D12_RESOURCE_DESC rd{};rd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;rd.Width=bytes;rd.Height=1;rd.DepthOrArraySize=rd.MipLevels=1;rd.SampleDesc.Count=1;rd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
 D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;ID3D12Resource*shared=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_SHARED,&rd,D3D12_RESOURCE_STATE_COMMON,nullptr,IID_PPV_ARGS(&shared)),"shared buffer");HANDLE sharedHandle=nullptr;ck(d->CreateSharedHandle(shared,nullptr,GENERIC_ALL,nullptr,&sharedHandle),"share handle");
 auto info=d->GetResourceAllocationInfo(0,1,&rd);MemoryDesc md{};md.type=type;md.handle.win32.handle=sharedHandle;md.size=info.SizeInBytes;md.flags=dedicated;Handle imported=nullptr;int result=hip.hipImportExternalMemory(&imported,&md);printf("import_memory=%d %s allocation=%llu\n",result,hip.hipGetErrorName(result),info.SizeInBytes);fflush(stdout);hip.Check(result,"import memory");BufferDesc bd{};bd.size=bytes;void*mapped=nullptr;hip.Check(hip.hipExternalMemoryGetMappedBuffer(&mapped,imported,&bd),"map buffer");
 ID3D12Fence*fence=nullptr;ck(d->CreateFence(0,D3D12_FENCE_FLAG_SHARED,IID_PPV_ARGS(&fence)),"fence");HANDLE fenceHandle=nullptr;ck(d->CreateSharedHandle(fence,nullptr,GENERIC_ALL,nullptr,&fenceHandle),"fence handle");SemaphoreDesc sd{};sd.type=4;sd.handle.win32.handle=fenceHandle;Handle semaphore=nullptr;result=hip.hipImportExternalSemaphore(&semaphore,&sd);printf("import_fence=%d %s\n",result,hip.hipGetErrorName(result));fflush(stdout);hip.Check(result,"import fence");Handle stream=nullptr;hip.Check(hip.hipStreamCreate(&stream),"stream");
 hp.Type=D3D12_HEAP_TYPE_UPLOAD;ID3D12Resource*upload=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&rd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&upload)),"upload");void*p=nullptr;D3D12_RANGE none{};ck(upload->Map(0,&none,&p),"upload map");memset(p,0x37,bytes);upload->Unmap(0,nullptr);
 D3D12_RESOURCE_BARRIER barrier{};barrier.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;barrier.Transition={shared,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_DEST};c->ResourceBarrier(1,&barrier);c->CopyBufferRegion(shared,0,upload,0,bytes);std::swap(barrier.Transition.StateBefore,barrier.Transition.StateAfter);c->ResourceBarrier(1,&barrier);ck(c->Close(),"close");ID3D12CommandList*lists[]={c};q->ExecuteCommandLists(1,lists);ck(q->Signal(fence,1),"signal 1");
 WaitParams wait{};wait.params.fence.value=1;hip.Check(hip.hipWaitExternalSemaphoresAsync(&semaphore,&wait,1,stream),"HIP wait 1");hip.Check(hip.hipStreamSynchronize(stream),"wait completion");std::vector<unsigned char>initial(bytes);hip.Check(hip.hipMemcpy(initial.data(),mapped,bytes,2),"HIP read shared");for(auto v:initial)if(v!=0x37)throw std::runtime_error("D3D12 -> HIP data mismatch");
 Handle module=nullptr,kernel=nullptr;void*kernelInput=nullptr;const bool runMatrix=argc>4;
 if(runMatrix){
  hip.Check(hip.hipModuleLoad(&module,argv[4]),"load WMMA module");hip.Check(hip.hipModuleGetFunction(&kernel,module,"wmma_probe"),"WMMA function");
  std::vector<int>ones(128,0x38383838);hip.Check(hip.hipMalloc(&kernelInput,ones.size()*sizeof(int)),"WMMA input");hip.Check(hip.hipMemcpy(kernelInput,ones.data(),ones.size()*sizeof(int),1),"WMMA upload");
  void*args[]={&kernelInput,&mapped};hip.Check(hip.hipModuleLaunchKernel(kernel,1,1,1,32,1,1,0,stream,args,nullptr),"launch WMMA");
 }else hip.Check(hip.hipMemsetAsync(mapped,0xa5,bytes,stream),"HIP write shared");
 SignalParams signal{};signal.params.fence.value=2;hip.Check(hip.hipSignalExternalSemaphoresAsync(&semaphore,&signal,1,stream),"HIP signal 2");ck(q->Wait(fence,2),"D3D12 wait 2");
 hp.Type=D3D12_HEAP_TYPE_READBACK;ID3D12Resource*readback=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&rd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&readback)),"readback");ck(alloc->Reset(),"reset allocator");ck(c->Reset(alloc,nullptr),"reset list");barrier.Transition.StateBefore=D3D12_RESOURCE_STATE_COMMON;barrier.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;c->ResourceBarrier(1,&barrier);c->CopyBufferRegion(readback,0,shared,0,bytes);std::swap(barrier.Transition.StateBefore,barrier.Transition.StateAfter);c->ResourceBarrier(1,&barrier);ck(c->Close(),"close readback");q->ExecuteCommandLists(1,lists);ck(q->Signal(fence,3),"signal 3");HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);ck(fence->SetEventOnCompletion(3,event),"event");if(WaitForSingleObject(event,5000)!=WAIT_OBJECT_0)throw std::runtime_error("D3D12 completion timeout");ck(d->GetDeviceRemovedReason(),"device status");D3D12_RANGE range{0,bytes};ck(readback->Map(0,&range,&p),"readback map");if(runMatrix){for(unsigned i=0;i<256;i++)if(static_cast<float*>(p)[i]!=16.0f)throw std::runtime_error("WMMA shared output mismatch at "+std::to_string(i));}
 else for(UINT64 i=0;i<bytes;i++)if(static_cast<unsigned char*>(p)[i]!=0xa5)throw std::runtime_error("HIP -> D3D12 data mismatch");readback->Unmap(0,&none);
 printf("PASS D3D12 -> HIP %s -> D3D12 shared GPU buffer, shared fence values 1/2/3; no experimental D3D features\n",runMatrix?"FP8 WMMA":"memset");hip.Check(hip.hipStreamSynchronize(stream),"final sync");if(kernelInput)hip.hipFree(kernelInput);if(module)hip.hipModuleUnload(module);hip.hipFree(mapped);hip.hipDestroyExternalMemory(imported);hip.hipDestroyExternalSemaphore(semaphore);hip.hipStreamDestroy(stream);CloseHandle(sharedHandle);CloseHandle(fenceHandle);CloseHandle(event);readback->Release();upload->Release();shared->Release();fence->Release();c->Release();alloc->Release();q->Release();d->Release();adapter->Release();factory->Release();return 0;
}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
