// multihead_fast_validate ASSETS PRODUCTION_FFN_CSO FAST_MODULE OUTPUT_PREFIX [C]
// Original native_c64.hlsl scalar passes, no optimization flags, vs HIP reference.
#include <cmath>
#include <windows.h>
#include <dxgi1_6.h>
#include <d3d12.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include "hip_api.h"

#include "../../src/native_game_submission.h"
extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
using hip_probe::Handle;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::wstring wide(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,nullptr,0);std::wstring v(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s,-1,v.data(),n);v.resize(n-1);return v;}
static std::vector<float> read(const std::wstring&p,size_t count){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("weight missing/size");f.seekg(0);std::vector<float>v(count);if(!f.read(reinterpret_cast<char*>(v.data()),count*4))throw std::runtime_error("weight read");return v;}
static void save(const std::string&p,const std::vector<float>&v){std::ofstream f(p,std::ios::binary);if(!f.write(reinterpret_cast<const char*>(v.data()),v.size()*4))throw std::runtime_error("save failed "+p);}
static ID3D12Resource* buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE heap,bool uav=false){D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;desc.Width=bytes;desc.Height=1;desc.DepthOrArraySize=desc.MipLevels=1;desc.SampleDesc.Count=1;desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;desc.Flags=uav?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&desc,heap==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:uav?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void transition(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
static void clear_flags(){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){const wchar_t*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)_wputenv((n+L"=").c_str());}
static float fp8(unsigned b){unsigned e=(b>>3)&15,m=b&7;float x=e?std::ldexp(1.f+m/8.f,int(e)-7):m/512.f;return b&128?-x:x;}
struct Comparison {size_t bits{},numeric{},invalid{};double maxabs{};};
static Comparison compare(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())throw std::runtime_error("compare size");Comparison r;for(size_t i=0;i<a.size();i++){unsigned x,y;memcpy(&x,&a[i],4);memcpy(&y,&b[i],4);r.bits+=x!=y;r.numeric+=a[i]!=b[i];r.invalid+=!std::isfinite(a[i])||!std::isfinite(b[i]);if(std::isfinite(a[i])&&std::isfinite(b[i]))r.maxabs=std::max(r.maxabs,std::abs(double(a[i])-b[i]));}return r;}
static unsigned char exact8(float v){for(unsigned b=0;b<256;b++)if((b&127)<127&&fp8(b)==v)return static_cast<unsigned char>(b);throw std::runtime_error("nonfinite/non-FP8 matrix operand");}
int main(int argc,char**argv){try{
 if(argc!=5&&argc!=6){puts("usage: multihead_fast_validate ASSETS PRODUCTION_FFN_CSO FAST_MODULE OUTPUT_PREFIX [C=64|128|256]");return 2;}clear_flags();unsigned C=argc==6?unsigned(std::stoul(argv[5])):64;if(C!=64&&C!=128&&C!=256)throw std::runtime_error("channels");unsigned block=C==64?5:C==128?9:15;auto dir=wide(argv[1]);auto fw=read(dir+L"\\block"+std::to_wstring(block)+L"-ffn.f32",9*C*C+C);unsigned W=20,H=20,T=W*H,hiddenC=4*C;std::string prefix=argv[4];std::ofstream report(prefix+"-report.txt");if(!report)throw std::runtime_error("output prefix");
 std::vector<unsigned char>packed(8*C*C);for(unsigned n=0;n<hiddenC;n++)for(unsigned k=0;k<C;k++)packed[((n/16)*(C/32)+k/32)*512+(k%32)*16+n%16]=exact8(fw[n*C+k]);for(unsigned n=0;n<C;n++)for(unsigned k=0;k<hiddenC;k++)packed[hiddenC*C+((n/16)*(hiddenC/32)+k/32)*512+(k%32)*16+n%16]=exact8(fw[hiddenC*C+n*hiddenC+k]);
 const IID experimental={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&experimental,nullptr,nullptr));IDXGIFactory1*f=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD missing");ID3D12CommandQueue*q{};D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission sub;sub.Create(q,false);
 D3D12_ROOT_PARAMETER p[4]{};p[0].ParameterType=p[1].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;p[1].Descriptor.ShaderRegister=1;p[2].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;p[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;p[3].Constants={0,0,2};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=4;rd.pParameters=p;ID3DBlob*b{},*e{};ck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&b,&e));if(e)e->Release();ID3D12RootSignature*root{};ck(d->CreateRootSignature(0,b->GetBufferPointer(),b->GetBufferSize(),IID_PPV_ARGS(&root)));b->Release();b=nullptr;ck(D3DReadFileToBlob(wide(argv[2]).c_str(),&b));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={b->GetBufferPointer(),b->GetBufferSize()};ID3D12PipelineState*pso{};ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));b->Release();
 auto*weights=buffer(d,packed.size(),D3D12_HEAP_TYPE_UPLOAD),*input=buffer(d,T*C,D3D12_HEAP_TYPE_UPLOAD),*output=buffer(d,T*C,D3D12_HEAP_TYPE_DEFAULT,true),*rb=buffer(d,T*C,D3D12_HEAP_TYPE_READBACK),*sentinel=buffer(d,T*C,D3D12_HEAP_TYPE_UPLOAD);D3D12_RANGE none{};void*m{};ck(weights->Map(0,&none,&m));memcpy(m,packed.data(),packed.size());weights->Unmap(0,nullptr);ck(sentinel->Map(0,&none,&m));memset(m,0xff,T*C);sentinel->Unmap(0,nullptr);
 hip_probe::Api hip;hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle module{};hip.Check(hip.hipModuleLoad(&module,argv[3]),"module");void*hi{},*hw{},*hh{},*ho{};hip.Check(hip.hipMalloc(&hi,T*C*4),"input alloc");hip.Check(hip.hipMalloc(&hw,fw.size()*4),"weights alloc");hip.Check(hip.hipMalloc(&hh,T*hiddenC*4),"hidden alloc");hip.Check(hip.hipMalloc(&ho,T*C*4),"out alloc");hip.Check(hip.hipMemcpy(hw,fw.data(),fw.size()*4,1),"weights upload");
 size_t diff=0,invalid=0;for(unsigned pattern=0;pattern<2;pattern++){std::vector<float>src(T*C);std::vector<unsigned char>src8(T*C);for(unsigned i=0;i<src.size();i++){src8[i]=static_cast<unsigned char>(((i*(pattern?53:37)+(pattern?29:11))%80)|((i%(pattern?5:3)==0)?128:0));src[i]=fp8(src8[i]);}std::string base=prefix+"-p"+std::to_string(pattern);save(base+"-input.f32",src);ck(input->Map(0,&none,&m));memcpy(m,src8.data(),src8.size());input->Unmap(0,nullptr);unsigned geometry[]={W,H};
 sub.Submit([&](ID3D12GraphicsCommandList*c){transition(c,output,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_DEST);c->CopyBufferRegion(output,0,sentinel,0,T*C);transition(c,output,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);c->SetComputeRootSignature(root);c->SetPipelineState(pso);c->SetComputeRootShaderResourceView(0,input->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,weights->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(2,output->GetGPUVirtualAddress());c->SetComputeRoot32BitConstants(3,2,geometry,0);c->Dispatch(T/16,1,1);transition(c,output,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,output,0,T*C);transition(c,output,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);});sub.Flush();std::vector<float>expected(T*C);D3D12_RANGE range{0,T*C};ck(rb->Map(0,&range,&m));for(unsigned i=0;i<T*C;i++){unsigned bits=static_cast<unsigned char*>(m)[i];expected[i]=(bits&127)==127?std::nanf(""):fp8(bits);}rb->Unmap(0,&none);
 hip.Check(hip.hipMemcpy(hi,src.data(),src.size()*4,1),"input upload");hip.Check(hip.hipMemsetAsync(ho,0xff,T*C*4,nullptr),"HIP sentinel");Handle expand{},contract{};hip.Check(hip.hipModuleGetFunction(&expand,module,"mh_ffn_expand_fast"),"expand fn");hip.Check(hip.hipModuleGetFunction(&contract,module,"mh_ffn_contract_fast"),"contract fn");void*ea[]={&hi,&hw,&hh,&T,&C},*ca[]={&hh,&hw,&ho,&T,&C};hip.Check(hip.hipModuleLaunchKernel(expand,((T+63)/64)*((4*C+63)/64),1,1,512,1,1,0,nullptr,ea,nullptr),"expand");hip.Check(hip.hipModuleLaunchKernel(contract,((T+63)/64)*((C+63)/64),1,1,512,1,1,0,nullptr,ca,nullptr),"contract");hip.Check(hip.hipDeviceSynchronize(),"HIP completion");std::vector<float>got(T*C),hidden(T*hiddenC);hip.Check(hip.hipMemcpy(got.data(),ho,got.size()*4,2),"out read");hip.Check(hip.hipMemcpy(hidden.data(),hh,hidden.size()*4,2),"hidden read");save(base+"-production-contract.f32",expected);save(base+"-hip-contract.f32",got);save(base+"-hip-hidden.f32",hidden);auto r=compare(expected,got);diff+=r.bits;invalid+=r.invalid;printf("C=%u M=%u pattern=%u production_fusedFFN_vs_HIPfast count=%zu bitdiff=%zu invalid=%zu maxabs=%.9g\n",C,T,pattern,got.size(),r.bits,r.invalid,r.maxabs);report<<"pattern="<<pattern<<" count="<<got.size()<<" bitdiff="<<r.bits<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";// Reuse identical HIP hidden for raw-accumulator and RTZ epilogue diagnostics.
 for(const char*tag:{"pre","rtz","rne"}){std::string entry="mh_ffn_contract_fast_"+std::string(tag);Handle fn{};hip.Check(hip.hipModuleGetFunction(&fn,module,entry.c_str()),"diagnostic entry");hip.Check(hip.hipModuleLaunchKernel(fn,((T+63)/64)*((C+63)/64),1,1,512,1,1,0,nullptr,ca,nullptr),"diagnostic contract");hip.Check(hip.hipDeviceSynchronize(),"diagnostic sync");std::vector<float>v(T*C);hip.Check(hip.hipMemcpy(v.data(),ho,v.size()*4,2),"diagnostic read");save(base+"-hip-contract-"+tag+".f32",v);if(strcmp(tag,"pre")){auto z=compare(expected,v);printf("ROUND_DIAGNOSTIC mode=%s C=%u pattern=%u bitdiff=%zu invalid=%zu maxabs=%.9g\n",tag,C,pattern,z.bits,z.invalid,z.maxabs);report<<tag<<" pattern="<<pattern<<" bitdiff="<<z.bits<<" invalid="<<z.invalid<<" maxabs="<<z.maxabs<<"\n";}}
 fflush(stdout);report.flush();}
 hip.Check(hip.hipDeviceSynchronize(),"final sync");for(auto ptr:{hi,hw,hh,ho})hip.Check(hip.hipFree(ptr),"free");hip.Check(hip.hipModuleUnload(module),"unload");for(auto*r:{weights,input,output,rb,sentinel})r->Release();pso->Release();root->Release();q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",diff,invalid);return invalid?1:diff?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
