// multihead_fast_validate ASSETS PRODUCTION_FFN_CSO FAST_MODULE OUTPUT_PREFIX [C]
// Original native_c64.hlsl scalar passes, no optimization flags, vs HIP reference.
#include <cmath>
#include <windows.h>
#include <dxgi1_6.h>
#include <d3d12.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include "hip_api.h"

#include "../../src/native_game_submission.h"
extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
using hip_probe::Handle;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::wstring wide(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,nullptr,0);std::wstring v(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s,-1,v.data(),n);v.resize(n-1);return v;}
static std::vector<float> read(const std::wstring&p,size_t count){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("weight missing/size");f.seekg(0);std::vector<float>v(count);if(!f.read(reinterpret_cast<char*>(v.data()),count*4))throw std::runtime_error("weight read");return v;}
static void save(const std::string&p,const std::vector<float>&v){std::ofstream f(p,std::ios::binary);if(!f.write(reinterpret_cast<const char*>(v.data()),v.size()*4))throw std::runtime_error("save failed "+p);}
static ID3D12Resource* buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE heap,bool uav=false){D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;desc.Width=bytes;desc.Height=1;desc.DepthOrArraySize=desc.MipLevels=1;desc.SampleDesc.Count=1;desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;desc.Flags=uav?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&desc,heap==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:uav?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void transition(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
static void clear_flags(){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){const wchar_t*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)_wputenv((n+L"=").c_str());}
static float fp8(unsigned b){unsigned e=(b>>3)&15,m=b&7;float x=e?std::ldexp(1.f+m/8.f,int(e)-7):m/512.f;return b&128?-x:x;}
struct Comparison {size_t bits{},numeric{},invalid{};double maxabs{};};
static Comparison compare(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())throw std::runtime_error("compare size");Comparison r;for(size_t i=0;i<a.size();i++){unsigned x,y;memcpy(&x,&a[i],4);memcpy(&y,&b[i],4);r.bits+=x!=y;r.numeric+=a[i]!=b[i];r.invalid+=!std::isfinite(a[i])||!std::isfinite(b[i]);if(std::isfinite(a[i])&&std::isfinite(b[i]))r.maxabs=std::max(r.maxabs,std::abs(double(a[i])-b[i]));}return r;}
static unsigned char exact8(float v){for(unsigned b=0;b<256;b++)if((b&127)<127&&fp8(b)==v)return static_cast<unsigned char>(b);throw std::runtime_error("nonfinite/non-FP8 matrix operand");}
static unsigned char nearest8(float v){unsigned best=0;double error=1e100;for(unsigned b=0;b<127;b++){double e=std::abs(double(std::abs(v))-fp8(b));if(e<error||(e==error&&!(b&1))){best=b;error=e;}}return static_cast<unsigned char>(best|(v<0?128:0));}
static std::vector<char> bytes(const std::vector<float>&v){std::vector<char>b(v.size()*4);memcpy(b.data(),v.data(),b.size());return b;}
struct Prod {
 ID3D12Device*d;NativeGameSubmission&sub;ID3D12RootSignature*root{};
 Prod(ID3D12Device*device,NativeGameSubmission&s):d(device),sub(s){D3D12_ROOT_PARAMETER p[5]{};for(unsigned i=0;i<3;i++){p[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;p[i].Descriptor.ShaderRegister=i;}p[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;p[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;p[4].Constants={0,0,6};D3D12_ROOT_SIGNATURE_DESC r{};r.NumParameters=5;r.pParameters=p;ID3DBlob*b{},*e{};ck(D3D12SerializeRootSignature(&r,D3D_ROOT_SIGNATURE_VERSION_1,&b,&e));if(e)e->Release();ck(d->CreateRootSignature(0,b->GetBufferPointer(),b->GetBufferSize(),IID_PPV_ARGS(&root)));b->Release();}
 ~Prod(){root->Release();}
 std::vector<float>run8(const char*cso,const std::vector<char>&a,const std::vector<char>&b,const std::vector<char>&c,unsigned W,unsigned H,unsigned C,unsigned gx,unsigned gy,unsigned post=4){
  ID3DBlob*blob{};ck(D3DReadFileToBlob(wide(cso).c_str(),&blob));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ID3D12PipelineState*pso{};ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));blob->Release();
  const std::vector<char>*in[]={&a,&b,&c};ID3D12Resource*gpu[3]{};D3D12_RANGE none{};void*m{};for(unsigned i=0;i<3;i++){gpu[i]=buffer(d,in[i]->size(),D3D12_HEAP_TYPE_UPLOAD);ck(gpu[i]->Map(0,&none,&m));memcpy(m,in[i]->data(),in[i]->size());gpu[i]->Unmap(0,nullptr);}unsigned n=W*H*C,nb=n*(post==4?1:4);auto*out=buffer(d,nb,D3D12_HEAP_TYPE_DEFAULT,true),*rb=buffer(d,nb,D3D12_HEAP_TYPE_READBACK),*sentinel=buffer(d,nb,D3D12_HEAP_TYPE_UPLOAD);ck(sentinel->Map(0,&none,&m));memset(m,0xff,nb);sentinel->Unmap(0,nullptr);unsigned g[]={W,H,W,H,0,0};
  sub.Submit([&](ID3D12GraphicsCommandList*l){transition(l,out,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_DEST);l->CopyBufferRegion(out,0,sentinel,0,nb);transition(l,out,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);l->SetComputeRootSignature(root);l->SetPipelineState(pso);for(unsigned i=0;i<3;i++)l->SetComputeRootShaderResourceView(i,gpu[i]->GetGPUVirtualAddress());l->SetComputeRootUnorderedAccessView(3,out->GetGPUVirtualAddress());l->SetComputeRoot32BitConstants(4,6,g,0);l->Dispatch(gx,gy,1);transition(l,out,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);l->CopyBufferRegion(rb,0,out,0,nb);});sub.Flush();D3D12_RANGE range{0,nb};ck(rb->Map(0,&range,&m));std::vector<float>v(n);if(post==4){for(unsigned i=0;i<n;i++){unsigned q=static_cast<unsigned char*>(m)[i];v[i]=(q&127)==127?std::nanf(""):fp8(q);}}else memcpy(v.data(),m,nb);rb->Unmap(0,&none);for(auto*r:gpu)r->Release();out->Release();rb->Release();sentinel->Release();pso->Release();return v;
 }
};
int main(int argc,char**argv){try{
 if(argc!=7&&argc!=9){puts("Usage: multihead_fused_attention_validate.exe ASSETS STAGED_MODULE FUSED_MODULE PRODUCTION_ATTN_CSO OUTPUT_PREFIX C64|128|256|512 [WIDTH HEIGHT]");return 2;}clear_flags();unsigned C=std::stoul(argv[6]),W=argc==9?std::stoul(argv[7]):16,H=argc==9?std::stoul(argv[8]):16;if((C!=64&&C!=128&&C!=256&&C!=512)||!W||!H||W%8||H%8||W>128||H>128)throw std::runtime_error("geometry");unsigned heads=C/32,T=W*H,windows=T/64,block=C==64?5:C==128?9:C==256?15:23;auto aw=read(wide(argv[1])+L"\\block"+std::to_wstring(block)+L"-attention.f32",4*C*C+heads*4096+heads+C);std::string prefix=argv[5];std::ofstream report(prefix+"-report.txt");if(!report)throw std::runtime_error("report");
 const IID experimental={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&experimental,nullptr,nullptr));IDXGIFactory1*f{};ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d{};for(unsigned i=0;;i++){IDXGIAdapter1*a{};if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 ds{};a->GetDesc1(&ds);if(ds.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD missing");ID3D12CommandQueue*q{};D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission sub;sub.Create(q,false);Prod prod(d,sub);
 hip_probe::Api hip(7);hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle staged{},fused{};hip.Check(hip.hipModuleLoad(&staged,argv[2]),"staged module");hip.Check(hip.hipModuleLoad(&fused,argv[3]),"fused module");std::vector<void*>owned;auto alloc=[&](size_t n){void*p{};hip.Check(hip.hipMalloc(&p,n*4),"alloc");owned.push_back(p);return p;};void*norm=alloc(T*3*C),*hw=alloc(aw.size()),*ex=alloc(windows*heads*4096),*prob=alloc(windows*heads*4096),*av=alloc(T*C),*out=alloc(T*C);hip.Check(hip.hipMemcpy(hw,aw.data(),aw.size()*4,1),"weights");auto run=[&](Handle module,const char*n,unsigned groups,unsigned threads,std::initializer_list<void*>args){Handle fn{};hip.Check(hip.hipModuleGetFunction(&fn,module,n),n);std::vector<void*>p(args);hip.Check(hip.hipModuleLaunchKernel(fn,groups,1,1,threads,1,1,0,nullptr,p.data(),nullptr),n);};size_t total=0,invalid=0;
 for(unsigned pat=0;pat<2;pat++){std::string base=prefix+"-p"+std::to_string(pat);std::vector<float>normalized(T*3*C);std::vector<char>win8(T*3*C);for(unsigned p=0;p<T;p++){unsigned win=p/W/8*(W/8)+(p%W)/8,tok=(p/W%8)*8+p%8;for(unsigned c=0;c<3*C;c++){unsigned i=p*3*C+c,b=((i*(pat?53:37)+11)%57)|((i%3==0)?128:0);normalized[i]=fp8(b);win8[(win*64+tok)*3*C+c]=char(b);}}save(base+"-input.f32",normalized);auto oracle=prod.run8(argv[4],bytes(normalized),bytes(aw),win8,W,H,C,windows,heads);hip.Check(hip.hipMemcpy(norm,normalized.data(),normalized.size()*4,1),"normalized upload");hip.Check(hip.hipMemsetAsync(av,0xff,T*C*4,nullptr),"staged sentinel");hip.Check(hip.hipMemsetAsync(out,0xff,T*C*4,nullptr),"fused sentinel");run(staged,"mh_scores_exp_fast",windows*heads*16,32,{&norm,&hw,&ex,&W,&H,&C});run(staged,"mh_probabilities_fast",windows*heads*4,32,{&ex,&prob,&windows,&C});run(staged,"mh_attention_av_fast",windows*heads*8,32,{&prob,&norm,&av,&W,&H,&C});run(fused,"mh_attention_fused",windows*heads,128,{&norm,&hw,&out,&W,&H,&C});hip.Check(hip.hipDeviceSynchronize(),"attention completion");std::vector<float>a(T*C),b(T*C);hip.Check(hip.hipMemcpy(a.data(),av,a.size()*4,2),"read staged");hip.Check(hip.hipMemcpy(b.data(),out,b.size()*4,2),"read fused");save(base+"-production.f32",oracle);save(base+"-staged.f32",a);save(base+"-fused.f32",b);auto check=[&](const char*tag,const std::vector<float>&x,const std::vector<float>&y){auto r=compare(x,y);total+=r.bits;invalid+=r.invalid;printf("C=%u W=%u H=%u pattern=%u %s bitdiff=%zu numericdiff=%zu invalid=%zu maxabs=%.9g\n",C,W,H,pat,tag,r.bits,r.numeric,r.invalid,r.maxabs);report<<"C="<<C<<" W="<<W<<" H="<<H<<" pattern="<<pat<<" stage="<<tag<<" bitdiff="<<r.bits<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";};check("production-vs-staged",oracle,a);check("staged-vs-fused",a,b);check("production-vs-fused",oracle,b);fflush(stdout);report.flush();}
 hip.Check(hip.hipDeviceSynchronize(),"sync");for(void*p:owned)hip.Check(hip.hipFree(p),"free");hip.Check(hip.hipModuleUnload(staged),"staged unload");hip.Check(hip.hipModuleUnload(fused),"fused unload");q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",total,invalid);return invalid?1:total?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
