// multihead_fast_validate ASSETS PRODUCTION_FFN_CSO FAST_MODULE OUTPUT_PREFIX [C]
// Original native_c64.hlsl scalar passes, no optimization flags, vs HIP reference.
#include <cmath>
#include <windows.h>
#include <dxgi1_6.h>
#include <d3d12.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include "hip_api.h"

#include "../../src/native_game_submission.h"
extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
using hip_probe::Handle;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::wstring wide(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,nullptr,0);std::wstring v(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s,-1,v.data(),n);v.resize(n-1);return v;}
static std::vector<float> read(const std::wstring&p,size_t count){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("weight missing/size");f.seekg(0);std::vector<float>v(count);if(!f.read(reinterpret_cast<char*>(v.data()),count*4))throw std::runtime_error("weight read");return v;}
static void save(const std::string&p,const std::vector<float>&v){std::ofstream f(p,std::ios::binary);if(!f.write(reinterpret_cast<const char*>(v.data()),v.size()*4))throw std::runtime_error("save failed "+p);}
static ID3D12Resource* buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE heap,bool uav=false){D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;desc.Width=bytes;desc.Height=1;desc.DepthOrArraySize=desc.MipLevels=1;desc.SampleDesc.Count=1;desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;desc.Flags=uav?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&desc,heap==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:uav?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void transition(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
static void clear_flags(){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){const wchar_t*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)_wputenv((n+L"=").c_str());}
static float fp8(unsigned b){unsigned e=(b>>3)&15,m=b&7;float x=e?std::ldexp(1.f+m/8.f,int(e)-7):m/512.f;return b&128?-x:x;}
struct Comparison {size_t bits{},numeric{},invalid{};double maxabs{};};
static Comparison compare(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())throw std::runtime_error("compare size");Comparison r;for(size_t i=0;i<a.size();i++){unsigned x,y;memcpy(&x,&a[i],4);memcpy(&y,&b[i],4);r.bits+=x!=y;r.numeric+=a[i]!=b[i];r.invalid+=!std::isfinite(a[i])||!std::isfinite(b[i]);if(std::isfinite(a[i])&&std::isfinite(b[i]))r.maxabs=std::max(r.maxabs,std::abs(double(a[i])-b[i]));}return r;}
static unsigned char exact8(float v){for(unsigned b=0;b<256;b++)if((b&127)<127&&fp8(b)==v)return static_cast<unsigned char>(b);throw std::runtime_error("nonfinite/non-FP8 matrix operand");}
static unsigned char nearest8(float v){unsigned best=0;double error=1e100;for(unsigned b=0;b<127;b++){double e=std::abs(double(std::abs(v))-fp8(b));if(e<error||(e==error&&!(b&1))){best=b;error=e;}}return static_cast<unsigned char>(best|(v<0?128:0));}
static std::vector<char> bytes(const std::vector<float>&v){std::vector<char>b(v.size()*4);memcpy(b.data(),v.data(),b.size());return b;}
struct Prod {
 ID3D12Device*d;NativeGameSubmission&sub;ID3D12RootSignature*root{};
 Prod(ID3D12Device*device,NativeGameSubmission&s):d(device),sub(s){D3D12_ROOT_PARAMETER p[5]{};for(unsigned i=0;i<3;i++){p[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;p[i].Descriptor.ShaderRegister=i;}p[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;p[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;p[4].Constants={0,0,6};D3D12_ROOT_SIGNATURE_DESC r{};r.NumParameters=5;r.pParameters=p;ID3DBlob*b{},*e{};ck(D3D12SerializeRootSignature(&r,D3D_ROOT_SIGNATURE_VERSION_1,&b,&e));if(e)e->Release();ck(d->CreateRootSignature(0,b->GetBufferPointer(),b->GetBufferSize(),IID_PPV_ARGS(&root)));b->Release();}
 ~Prod(){root->Release();}
 std::vector<float>run8(const char*cso,const std::vector<char>&a,const std::vector<char>&b,const std::vector<char>&c,unsigned W,unsigned H,unsigned C,unsigned gx,unsigned gy,unsigned post=4){
  ID3DBlob*blob{};ck(D3DReadFileToBlob(wide(cso).c_str(),&blob));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ID3D12PipelineState*pso{};ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));blob->Release();
  const std::vector<char>*in[]={&a,&b,&c};ID3D12Resource*gpu[3]{};D3D12_RANGE none{};void*m{};for(unsigned i=0;i<3;i++){gpu[i]=buffer(d,in[i]->size(),D3D12_HEAP_TYPE_UPLOAD);ck(gpu[i]->Map(0,&none,&m));memcpy(m,in[i]->data(),in[i]->size());gpu[i]->Unmap(0,nullptr);}unsigned n=W*H*C,nb=n*(post==4?1:4);auto*out=buffer(d,nb,D3D12_HEAP_TYPE_DEFAULT,true),*rb=buffer(d,nb,D3D12_HEAP_TYPE_READBACK),*sentinel=buffer(d,nb,D3D12_HEAP_TYPE_UPLOAD);ck(sentinel->Map(0,&none,&m));memset(m,0xff,nb);sentinel->Unmap(0,nullptr);unsigned g[]={W,H,W,0,0,0};
  sub.Submit([&](ID3D12GraphicsCommandList*l){transition(l,out,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_DEST);l->CopyBufferRegion(out,0,sentinel,0,nb);transition(l,out,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);l->SetComputeRootSignature(root);l->SetPipelineState(pso);for(unsigned i=0;i<3;i++)l->SetComputeRootShaderResourceView(i,gpu[i]->GetGPUVirtualAddress());l->SetComputeRootUnorderedAccessView(3,out->GetGPUVirtualAddress());l->SetComputeRoot32BitConstants(4,6,g,0);l->Dispatch(gx,gy,1);transition(l,out,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);l->CopyBufferRegion(rb,0,out,0,nb);});sub.Flush();D3D12_RANGE range{0,nb};ck(rb->Map(0,&range,&m));std::vector<float>v(n);if(post==4){for(unsigned i=0;i<n;i++){unsigned q=static_cast<unsigned char*>(m)[i];v[i]=(q&127)==127?std::nanf(""):fp8(q);}}else memcpy(v.data(),m,nb);rb->Unmap(0,&none);for(auto*r:gpu)r->Release();out->Release();rb->Release();sentinel->Release();pso->Release();return v;
 }
};
static unsigned short hbits(float f){unsigned b;memcpy(&b,&f,4);unsigned s=(b>>16)&0x8000,a=b&0x7fffffff;if(a>=0x7f800000)return static_cast<unsigned short>(s|0x7c00|(a>0x7f800000?0x200:0));int e=int(a>>23)-127;unsigned m=(a&0x7fffff)|0x800000;if(e>15)return static_cast<unsigned short>(s|0x7c00);if(e<-25)return static_cast<unsigned short>(s);unsigned shift=e<-14?unsigned(-e-1):13,q=m>>shift,r=m&((1u<<shift)-1),h=1u<<(shift-1);q+=r>h||(r==h&&(q&1));return static_cast<unsigned short>(s|(e<-14?q:((e+14)<<10)+q));}
static float fromhalf(unsigned h){unsigned e=(h>>10)&31,m=h&1023;float x=e==31?(m?std::nanf(""):INFINITY):e?std::ldexp(1.f+m/1024.f,int(e)-15):std::ldexp(float(m),-24);return h&0x8000?-x:x;}
static std::vector<char> packhalf(const std::vector<float>&v){std::vector<char>b(v.size()*2);for(size_t i=0;i<v.size();i++){auto h=hbits(v[i]);if(!std::isfinite(v[i])||fromhalf(h)!=v[i])throw std::runtime_error("not exact finite half operand");memcpy(b.data()+i*2,&h,2);}return b;}
int main(int argc,char**argv){try{
 if(argc!=6){puts("usage: multihead_pool_production_validate ASSETS FAST_MODULE POOL_PROJECT_CSO PREFIX C32|64|128|256|512");return 2;}clear_flags();unsigned C=std::stoul(argv[5]);if(C!=32&&C!=64&&C!=128&&C!=256&&C!=512)throw std::runtime_error("channels");unsigned ds=C==32?4:C==64?8:C==128?14:22,W=16,H=16,T=W*H,zero=0;auto dir=wide(argv[1]);auto weights=read(dir+(C==512?L"\\head-matrix.f32":L"\\block"+std::to_wstring(ds)+L"-ds.f32"),2*C*C);std::string prefix=argv[4];std::ofstream report(prefix+"-report.txt");if(!report)throw std::runtime_error("output prefix");std::vector<char>packedWeights;if(C==32){packedWeights.resize(weights.size());for(size_t i=0;i<weights.size();i++)packedWeights[i]=char(exact8(weights[i]));}else packedWeights=packhalf(weights);
 const IID experimental={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&experimental,nullptr,nullptr));IDXGIFactory1*f{};ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d{};for(unsigned i=0;;i++){IDXGIAdapter1*a{};if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD missing");ID3D12CommandQueue*q{};D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission sub;sub.Create(q,false);Prod prod(d,sub);
 hip_probe::Api hip;hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle mod{},fn{};hip.Check(hip.hipModuleLoad(&mod,argv[2]),"module");hip.Check(hip.hipModuleGetFunction(&fn,mod,"mh_pool_project_production"),"function");void*in{},*hw{},*out{};hip.Check(hip.hipMalloc(&in,T*C*4),"input alloc");hip.Check(hip.hipMalloc(&hw,weights.size()*4),"weights alloc");hip.Check(hip.hipMalloc(&out,T*2*C*4),"output alloc");hip.Check(hip.hipMemcpy(hw,weights.data(),weights.size()*4,1),"weights");size_t total=0,invalid=0;
 for(unsigned pat=0;pat<2;pat++){std::vector<float>pooled(T*C);for(unsigned i=0;i<pooled.size();i++)pooled[i]=fp8(((i*(pat?53:37)+11)%80)|((i%3==0)?128:0));auto inputBytes=C==32?bytes(pooled):packhalf(pooled);auto expected=prod.run8(argv[3],inputBytes,packedWeights,inputBytes,W,H,2*C,T/16,C==32?1:2*C/16,0);hip.Check(hip.hipMemcpy(in,pooled.data(),pooled.size()*4,1),"input");hip.Check(hip.hipMemsetAsync(out,0xff,T*2*C*4,nullptr),"sentinel");void*args[]={&in,&hw,&out,&W,&H,&zero,&zero,&C};hip.Check(hip.hipModuleLaunchKernel(fn,((T+15)/16)*(2*C/16),1,1,32,1,1,0,nullptr,args,nullptr),"pool projection");hip.Check(hip.hipDeviceSynchronize(),"sync");std::vector<float>got(T*2*C);hip.Check(hip.hipMemcpy(got.data(),out,got.size()*4,2),"output read");auto r=compare(expected,got);total+=r.bits;invalid+=r.invalid;std::string base=prefix+"-p"+std::to_string(pat);save(base+"-pooled.f32",pooled);save(base+"-production.f32",expected);save(base+"-hip.f32",got);printf("C=%u pattern=%u pool_project count=%zu bitdiff=%zu invalid=%zu maxabs=%.9g\n",C,pat,got.size(),r.bits,r.invalid,r.maxabs);report<<"pattern="<<pat<<" bitdiff="<<r.bits<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";fflush(stdout);report.flush();}
 hip.Check(hip.hipDeviceSynchronize(),"finish");for(auto p:{in,hw,out})hip.Check(hip.hipFree(p),"free");hip.Check(hip.hipModuleUnload(mod),"unload");q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",total,invalid);return invalid?1:total?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
