// multihead_validate ASSETS MODULE OUTPUT_PREFIX [CHANNELS=64|512]
// Original native_c64.hlsl scalar passes, no optimization flags, vs HIP reference.
#include <cmath>
#include <windows.h>
#include <dxgi1_6.h>
#include <d3d12.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include "hip_api.h"

#include "../../src/native_game_submission.h"
using hip_probe::Handle;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::wstring wide(const char*s){int n=MultiByteToWideChar(CP_UTF8,0,s,-1,nullptr,0);std::wstring v(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s,-1,v.data(),n);v.resize(n-1);return v;}
static std::vector<float> read(const std::wstring&p,size_t count){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("weight missing/size");f.seekg(0);std::vector<float>v(count);if(!f.read(reinterpret_cast<char*>(v.data()),count*4))throw std::runtime_error("weight read");return v;}
static void save(const std::string&p,const std::vector<float>&v){std::ofstream f(p,std::ios::binary);if(!f.write(reinterpret_cast<const char*>(v.data()),v.size()*4))throw std::runtime_error("save failed "+p);}
static ID3D12Resource* buffer(ID3D12Device*d,size_t bytes,D3D12_HEAP_TYPE heap,bool uav=false){D3D12_RESOURCE_DESC desc{};desc.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;desc.Width=bytes;desc.Height=1;desc.DepthOrArraySize=desc.MipLevels=1;desc.SampleDesc.Count=1;desc.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;desc.Flags=uav?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&desc,heap==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:uav?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)));return r;}
static void transition(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
static void clear_flags(){wchar_t*env=GetEnvironmentStringsW();std::vector<std::wstring>names;for(auto*p=env;*p;p+=wcslen(p)+1)if(!wcsncmp(p,L"DLSS5_",6)){const wchar_t*e=wcschr(p,L'=');if(e)names.emplace_back(p,size_t(e-p));}FreeEnvironmentStringsW(env);for(auto&n:names)_wputenv((n+L"=").c_str());}
static float fp8(unsigned b){unsigned e=(b>>3)&15,m=b&7;float x=e?std::ldexp(1.f+m/8.f,int(e)-7):m/512.f;return b&128?-x:x;}
struct Comparison {size_t bits{},numeric{},invalid{};double maxabs{};};
static Comparison compare(const std::vector<float>&a,const std::vector<float>&b){if(a.size()!=b.size())throw std::runtime_error("compare size");Comparison r;for(size_t i=0;i<a.size();i++){unsigned x,y;memcpy(&x,&a[i],4);memcpy(&y,&b[i],4);r.bits+=x!=y;r.numeric+=a[i]!=b[i];r.invalid+=!std::isfinite(a[i])||!std::isfinite(b[i]);if(std::isfinite(a[i])&&std::isfinite(b[i]))r.maxabs=std::max(r.maxabs,std::abs(double(a[i])-b[i]));}return r;}
struct Oracle {
 ID3D12Device*d;ID3D12RootSignature*root{};ID3D12PipelineState*pso[3]{};unsigned channels;
 Oracle(ID3D12Device*dev,const std::wstring&dir,unsigned ch):d(dev),channels(ch){
  D3D12_ROOT_PARAMETER p[5]{};for(unsigned i=0;i<3;i++){p[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;p[i].Descriptor.ShaderRegister=i;}p[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;p[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;p[4].Constants={0,0,2};D3D12_ROOT_SIGNATURE_DESC desc{};desc.NumParameters=5;desc.pParameters=p;ID3DBlob*b=nullptr,*e=nullptr;ck(D3D12SerializeRootSignature(&desc,D3D_ROOT_SIGNATURE_VERSION_1,&b,&e));if(e)e->Release();ck(d->CreateRootSignature(0,b->GetBufferPointer(),b->GetBufferSize(),IID_PPV_ARGS(&root)));b->Release();
  std::string ct=std::to_string(ch);D3D_SHADER_MACRO macros[]={{"CHANNELS",ct.c_str()},{"RAW_OUTPUT","1"},{"NATIVE_FAST_FP8","0"},{"NATIVE_PRECOMPUTED_QKV","0"},{"NATIVE_WAVE_SCORES","0"},{"NATIVE_WAVE_AV","0"},{nullptr,nullptr}};const char*names[]={"ffn","attention","projection"};
  for(unsigned i=ch==512?1:0;i<3;i++){b=e=nullptr;auto h=D3DCompileFromFile((dir+L"\\native_c64.hlsl").c_str(),macros,D3D_COMPILE_STANDARD_FILE_INCLUDE,names[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b,&e);if(FAILED(h)){std::string msg=e?std::string((char*)e->GetBufferPointer(),e->GetBufferSize()):"shader compile";if(e)e->Release();throw std::runtime_error(msg);}if(e)e->Release();D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={b->GetBufferPointer(),b->GetBufferSize()};ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));b->Release();}
 }
 ~Oracle(){for(auto*p:pso)if(p)p->Release();if(root)root->Release();}
 std::vector<std::vector<float>> Run(NativeGameSubmission&sub,const std::vector<float>&in,const std::vector<float>&fw,const std::vector<float>&aw,unsigned w,unsigned h){
  std::vector<ID3D12Resource*>owned;auto upload=[&](const std::vector<float>&v){auto*r=buffer(d,v.size()*4,D3D12_HEAP_TYPE_UPLOAD);owned.push_back(r);void*p=nullptr;D3D12_RANGE no{};ck(r->Map(0,&no,&p));memcpy(p,v.data(),v.size()*4);r->Unmap(0,nullptr);return r;};auto*src=upload(in),*wf=fw.empty()?nullptr:upload(fw),*wa=upload(aw);ID3D12Resource*out[3]{};for(auto&v:out){v=buffer(d,in.size()*4,D3D12_HEAP_TYPE_DEFAULT,true);owned.push_back(v);}unsigned geom[]={w,h};
  sub.Submit([&](ID3D12GraphicsCommandList*c){for(unsigned i=channels==512?1:0;i<3;i++){auto*input=i==0?src:i==1?(channels==512?src:out[0]):out[1];auto*skip=channels==512?src:out[0];c->SetComputeRootSignature(root);c->SetPipelineState(pso[i]);c->SetComputeRootShaderResourceView(0,input->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,(i?wa:wf)->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(2,(i?skip:src)->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(3,out[i]->GetGPUVirtualAddress());c->SetComputeRoot32BitConstants(4,2,geom,0);c->Dispatch((w*h+63)/64,i==1?channels/32:1,1);transition(c,out[i],D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);}});sub.Flush();
  std::vector<std::vector<float>>result(3);if(channels==512)result[0]=in;
  for(unsigned i=channels==512?1:0;i<3;i++){auto*rb=buffer(d,in.size()*4,D3D12_HEAP_TYPE_READBACK);sub.Submit([&](ID3D12GraphicsCommandList*c){transition(c,out[i],D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,out[i],0,in.size()*4);transition(c,out[i],D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);});sub.Flush();D3D12_RANGE r{0,in.size()*4},no{};void*p=nullptr;ck(rb->Map(0,&r,&p));result[i].resize(in.size());memcpy(result[i].data(),p,in.size()*4);rb->Unmap(0,&no);rb->Release();}for(auto*r:owned)r->Release();return result;
 }
};
int main(int argc,char**argv){try{
 if(argc!=4&&argc!=5){puts("usage: multihead_validate ASSETS MODULE OUTPUT_PREFIX [CHANNELS=64|512]");return 2;}clear_flags();unsigned C=argc==5?unsigned(std::stoul(argv[4])):64;if(C!=64&&C!=512)throw std::runtime_error("host only C64/block5 or C512/block23 attention");const auto dir=wide(argv[1]);unsigned heads=C/32;auto aw=read(dir+(C==64?L"\\block5-attention.f32":L"\\block23-attention.f32"),4*C*C+heads*4096+heads+C);std::vector<float>fw;if(C==64)fw=read(dir+L"\\block5-ffn.f32",9*C*C+C);std::string prefix=argv[3];std::ofstream report(prefix+"-report.txt");if(!report)throw std::runtime_error("output directory missing");
 IDXGIFactory1*f=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD missing");ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission sub;sub.Create(q,false);Oracle oracle(d,dir,C);
 hip_probe::Api hip;hip.Check(hip.hipInit(0),"init");hip.Check(hip.hipSetDevice(0),"device");Handle module{};hip.Check(hip.hipModuleLoad(&module,argv[2]),"module");size_t totaldiff=0,totalinvalid=0;
 for(unsigned size=0;size<(C==64?2u:1u);size++){unsigned W=size?16:8,H=W,T=W*H,windows=T/64,raw=1;std::vector<void*>allocations;auto alloc=[&](size_t n){void*p{};hip.Check(hip.hipMalloc(&p,n*4),"malloc");allocations.push_back(p);return p;};void*hi=alloc(T*C),*hf=C==64?alloc(fw.size()):nullptr,*ha=alloc(aw.size()),*hidden=C==64?alloc(T*4*C):nullptr,*middle=C==64?alloc(T*C):nullptr,*ffn=alloc(T*C),*qkv=alloc(T*3*C),*norm=alloc(T*2*C),*ex=alloc(windows*heads*4096),*prob=alloc(windows*heads*4096),*av=alloc(T*C),*out=alloc(T*C);if(hf)hip.Check(hip.hipMemcpy(hf,fw.data(),fw.size()*4,1),"FW");hip.Check(hip.hipMemcpy(ha,aw.data(),aw.size()*4,1),"AW");
 auto launch=[&](const char*n,unsigned items,std::initializer_list<void*>args){Handle fn{};hip.Check(hip.hipModuleGetFunction(&fn,module,n),n);std::vector<void*>v(args);hip.Check(hip.hipModuleLaunchKernel(fn,(items+255)/256,1,1,256,1,1,0,nullptr,v.data(),nullptr),n);};
 auto attention=[&](){launch("mh_qkv",T*3*C,{&ffn,&ha,&qkv,&T,&C});launch("mh_normalize",T*heads,{&qkv,&ha,&norm,&T,&C});launch("mh_scores_exp",windows*heads*4096,{&norm,&ha,&ex,&W,&H,&C});launch("mh_probabilities",windows*heads*64,{&ex,&prob,&windows,&C});launch("mh_attention_av",T*C,{&prob,&qkv,&av,&W,&H,&C});launch("mh_attention_project",T*C,{&av,&ffn,&ha,&out,&T,&C,&raw});hip.Check(hip.hipDeviceSynchronize(),"attention completion");};
 for(unsigned pattern=0;pattern<2;pattern++){std::vector<float>input(T*C);for(unsigned i=0;i<input.size();i++)input[i]=pattern?float(int((i*73+19)%1024)-512)/512.f:fp8(((i*37+11)%80)|((i%3==0)?128:0));std::string base=prefix+"-w"+std::to_string(W)+"-p"+std::to_string(pattern);save(base+"-input.f32",input);auto expected=oracle.Run(sub,input,fw,aw,W,H);hip.Check(hip.hipMemcpy(hi,input.data(),input.size()*4,1),"input");for(void*p:{ffn,av,out})hip.Check(hip.hipMemsetAsync(p,0xff,T*C*4,nullptr),"sentinel");
 if(C==64){launch("mh_ffn_expand",T*4*C,{&hi,&hf,&hidden,&T,&C});launch("mh_ffn_contract",T*C,{&hidden,&hf,&middle,&T,&C});launch("mh_ffn_project",T*C,{&middle,&hi,&hf,&ffn,&T,&C});}else hip.Check(hip.hipMemcpy(ffn,input.data(),input.size()*4,1),"C512 attention input");attention();
 auto check=[&](const char*name,void*gpu,const std::vector<float>&ref){std::vector<float>v(ref.size());hip.Check(hip.hipMemcpy(v.data(),gpu,v.size()*4,2),"read result");save(base+"-d3d-"+name+".f32",ref);save(base+"-hip-"+name+".f32",v);auto r=compare(ref,v);totaldiff+=r.bits;totalinvalid+=r.invalid;printf("C=%u W=%u pattern=%u stage=%s count=%zu bitdiff=%zu numericdiff=%zu invalid=%zu maxabs=%.9g\n",C,W,pattern,name,v.size(),r.bits,r.numeric,r.invalid,r.maxabs);report<<"C="<<C<<" W="<<W<<" pattern="<<pattern<<" stage="<<name<<" count="<<v.size()<<" bitdiff="<<r.bits<<" numericdiff="<<r.numeric<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";};
 if(C==64)check("ffn",ffn,expected[0]);check("av",av,expected[1]);check("raw",out,expected[2]);
 // Isolate attention from FFN drift using exact oracle FFN on both paths.
 if(C==64){hip.Check(hip.hipMemcpy(ffn,expected[0].data(),expected[0].size()*4,1),"isolated attention input");attention();check("av-isolated",av,expected[1]);check("raw-isolated",out,expected[2]);}
 const char*names[]={"qkv","norm","ex","prob"};void*ptrs[]={qkv,norm,ex,prob};size_t counts[]={T*3*C,T*2*C,windows*heads*4096,windows*heads*4096};for(unsigned j=0;j<4;j++){std::vector<float>v(counts[j]);hip.Check(hip.hipMemcpy(v.data(),ptrs[j],v.size()*4,2),"debug stage");save(base+"-hip-"+names[j]+".f32",v);}fflush(stdout);report.flush();
 }
 hip.Check(hip.hipDeviceSynchronize(),"size completion");for(auto*p:allocations)hip.Check(hip.hipFree(p),"free");}
 hip.Check(hip.hipModuleUnload(module),"unload");q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",totaldiff,totalinvalid);return totalinvalid?1:totaldiff?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
