// Reuse host resource/file/comparison helpers; the C32 validation entry is not called.
#define main unused_c32_validation_main
#include "c32_validate.cpp"
#undef main
extern "C" {__declspec(dllexport) extern const UINT D3D12SDKVersion=721;__declspec(dllexport) const char*D3D12SDKPath=".\\D3D12\\";}
// prefix_fast_validate.exe ASSETS_DIR PREFIX_MODULE ORACLE_CSO OUTPUT_PREFIX
int main(int argc,char**argv){try{
 if(argc!=5){puts("usage: prefix_fast_validate.exe assets-dir prefix-module.hsaco oracle.cso output-prefix");return 2;}clear_flags();const auto dir=wide(argv[1]);auto fw=read(dir+L"\\block0-ffn.f32",8736),noise=std::vector<float>(1,0);std::string prefix=argv[4];std::ofstream report(prefix+"-report.txt");
 auto original_fw=fw;fw.assign(29824/4,0);auto*packbytes=reinterpret_cast<unsigned char*>(fw.data());
 for(unsigned block=0;block<2;block++)for(unsigned k=0;k<16;k++)for(unsigned c=0;c<16;c++){float v=original_fw[(block*16+c)*16+k];unsigned u;memcpy(&u,&v,4);unsigned mag=u&0x7fffffffu,sign=(u>>16)&0x8000u,h=sign;if(mag){int e=int(mag>>23)-127;if(e>=-14){if((mag&0x1fffu)||e>15)throw std::runtime_error("prefix weight not half exact");h=sign|((mag>>13)-0x1c000u);}else{float q=std::abs(v)*16777216.f;if(q!=std::floor(q)||q>1023)throw std::runtime_error("prefix subnormal not half exact");h=sign|unsigned(q);}}unsigned short half=static_cast<unsigned short>(h);memcpy(packbytes+27776+(block*512+k*16+c)*2,&half,2);}
 const IID experimental={0x76f5573e,0xf13a,0x40f5,{0xb2,0x97,0x81,0xce,0x9e,0x18,0x93,0x3f}};ck(D3D12EnableExperimentalFeatures(1,&experimental,nullptr,nullptr));
 const unsigned W=16,H=16,T=W*H;std::vector<float>rgba(T*4),history(T*4);
 for(unsigned p=0;p<T;p++){unsigned tile=p/64,x=(tile%(W/8))*8+p%8,y=(tile/(W/8))*8+(p%64)/8;for(unsigned c=0;c<4;c++)rgba[p*4+c]=c==3?1.f:float((x*13+y*31+c*47)%257)/256.f;for(unsigned c=0;c<4;c++)history[p*4+c]=c==3?1.f:float((p*23+c*37+11)%193)/192.f;}
 save(prefix+"-rgba-tiles.f32",rgba);save(prefix+"-history-raster.f32",history);
 IDXGIFactory1*f=nullptr;ck(CreateDXGIFactory1(IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;for(unsigned i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};a->GetDesc1(&desc);if(desc.VendorId==0x1002)D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d));a->Release();if(d)break;}f->Release();if(!d)throw std::runtime_error("AMD D3D device missing");
 ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q,false);
 std::vector<ID3D12Resource*>owned;auto upload=[&](const std::vector<float>&v){auto*r=buffer(d,v.size()*4,D3D12_HEAP_TYPE_UPLOAD);owned.push_back(r);void*m=nullptr;D3D12_RANGE none{};ck(r->Map(0,&none,&m));memcpy(m,v.data(),v.size()*4);r->Unmap(0,nullptr);return r;};
 ID3D12Resource*src[]={upload(fw),upload(rgba),upload(noise),upload(history)};
 D3D12_RESOURCE_DESC od{};od.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;od.Width=T*64*4;od.Height=1;od.DepthOrArraySize=od.MipLevels=1;od.SampleDesc.Count=1;od.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;od.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;ID3D12Resource*out=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));owned.push_back(out);auto*rb=buffer(d,T*64*4,D3D12_HEAP_TYPE_READBACK);owned.push_back(rb);
 D3D12_ROOT_PARAMETER params[6]{};for(unsigned i=0;i<4;i++){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;params[i].Descriptor.ShaderRegister=i;}params[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;params[5].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;params[5].Constants={0,0,5};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=6;rd.pParameters=params;ID3DBlob*blob=nullptr,*error=nullptr;ck(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&error));if(error)error->Release();error=nullptr;ID3D12RootSignature*root=nullptr;ck(d->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),IID_PPV_ARGS(&root)));blob->Release();blob=nullptr;
 ck(D3DReadFileToBlob(wide(argv[3]).c_str(),&blob));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));blob->Release();
 hip_probe::Api hip;hip.Check(hip.hipInit(0),"hipInit");hip.Check(hip.hipSetDevice(0),"hipSetDevice");Handle module=nullptr,fn=nullptr,project=nullptr;hip.Check(hip.hipModuleLoad(&module,argv[2]),"module");hip.Check(hip.hipModuleGetFunction(&fn,module,"dlss5_prefix_fast_features"),"prefix kernel");hip.Check(hip.hipModuleGetFunction(&project,module,"dlss5_prefix_fast_project"),"project kernel");std::vector<void*>allocations;auto hupload=[&](const std::vector<float>&v){void*p=nullptr;hip.Check(hip.hipMalloc(&p,v.size()*4),"malloc");allocations.push_back(p);hip.Check(hip.hipMemcpy(p,v.data(),v.size()*4,1),"upload");return p;};void*hw=hupload(original_fw),*hi=hupload(rgba),*hn=hupload(noise),*hh=hupload(history),*ho=nullptr,*debug=nullptr;hip.Check(hip.hipMalloc(&ho,T*32*4),"output malloc");allocations.push_back(ho);hip.Check(hip.hipMalloc(&debug,T*32*4),"features alloc");allocations.push_back(debug);
 size_t totaldiff=0,invalid=0;for(unsigned seed:{0u,123u})for(unsigned temporal:{0u,1u}){
  unsigned constants[]={seed,W,H,0,temporal};submit.Submit([&](ID3D12GraphicsCommandList*c){c->SetComputeRootSignature(root);c->SetPipelineState(pso);for(unsigned i=0;i<4;i++)c->SetComputeRootShaderResourceView(i,src[i]->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(4,out->GetGPUVirtualAddress());c->SetComputeRoot32BitConstants(5,5,constants,0);c->Dispatch((T+15)/16,1,1);transition(c,out,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,out,0,T*64*4);transition(c,out,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);});submit.Flush();std::vector<float>oracle(T*32),actual(T*32);void*m=nullptr;D3D12_RANGE range{0,T*64*4},none{};ck(rb->Map(0,&range,&m));memcpy(oracle.data(),m,T*32*4);std::vector<float>oracle_features(T*32);memcpy(oracle_features.data(),static_cast<char*>(m)+T*32*4,T*32*4);rb->Unmap(0,&none);
  hip.Check(hip.hipMemsetAsync(ho,0xff,T*32*4,nullptr),"sentinel");void*args[]={&hi,&hh,&debug,(void*)&W,(void*)&H,&seed,&temporal};hip.Check(hip.hipModuleLaunchKernel(fn,(T+255)/256,1,1,256,1,1,0,nullptr,args,nullptr),"prefix launch");void*pargs[]={&debug,&hw,&ho,(void*)&T};hip.Check(hip.hipModuleLaunchKernel(project,T/8,1,1,32,1,1,0,nullptr,pargs,nullptr),"project launch");hip.Check(hip.hipDeviceSynchronize(),"prefix synchronize");hip.Check(hip.hipMemcpy(actual.data(),ho,T*32*4,2),"output read");std::string tag=prefix+"-s"+std::to_string(seed)+"-t"+std::to_string(temporal);std::vector<float>features(T*32);hip.Check(hip.hipMemcpy(features.data(),debug,T*32*4,2),"features read");save(tag+"-d3d-features.f32",oracle_features);save(tag+"-hip-features.f32",features);auto fr=compare(oracle_features,features);totaldiff+=fr.bits;invalid+=fr.invalid;printf("FEATURES seed=%u temporal=%u bitdiff=%zu invalid=%zu maxabs=%.9g\n",seed,temporal,fr.bits,fr.invalid,fr.maxabs);report<<"FEATURES seed="<<seed<<" temporal="<<temporal<<" bitdiff="<<fr.bits<<" maxabs="<<fr.maxabs<<"\n";
  hip.Check(hip.hipMemcpy(debug,oracle_features.data(),T*32*4,1),"oracle features upload");hip.Check(hip.hipModuleLaunchKernel(project,T/8,1,1,32,1,1,0,nullptr,pargs,nullptr),"isolated project");hip.Check(hip.hipDeviceSynchronize(),"isolated sync");std::vector<float>isolated(T*32);hip.Check(hip.hipMemcpy(isolated.data(),ho,T*32*4,2),"isolated read");save(tag+"-hip-isolated-project.f32",isolated);auto ir=compare(oracle,isolated);totaldiff+=ir.bits;invalid+=ir.invalid;printf("PROJECT seed=%u temporal=%u bitdiff=%zu invalid=%zu maxabs=%.9g\n",seed,temporal,ir.bits,ir.invalid,ir.maxabs);report<<"PROJECT seed="<<seed<<" temporal="<<temporal<<" bitdiff="<<ir.bits<<" maxabs="<<ir.maxabs<<"\n";
  save(tag+"-d3d.f32",oracle);save(tag+"-hip.f32",actual);auto r=compare(oracle,actual);totaldiff+=r.bits;invalid+=r.invalid;printf("seed=%u temporal=%u count=%zu bitdiff=%zu numericdiff=%zu invalid=%zu maxabs=%.9g\n",seed,temporal,oracle.size(),r.bits,r.numeric,r.invalid,r.maxabs);report<<"seed="<<seed<<" temporal="<<temporal<<" count="<<oracle.size()<<" bitdiff="<<r.bits<<" numericdiff="<<r.numeric<<" invalid="<<r.invalid<<" maxabs="<<r.maxabs<<"\n";fflush(stdout);
 }
 hip.Check(hip.hipDeviceSynchronize(),"final sync");for(auto*p:allocations)hip.Check(hip.hipFree(p),"free");hip.Check(hip.hipModuleUnload(module),"unload");submit.Flush();for(auto*r:owned)r->Release();pso->Release();root->Release();q->Release();d->Release();printf("RESULT bitdiff=%zu invalid=%zu\n",totaldiff,invalid);return invalid?1:totaldiff?3:0;
 }catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
