// Cross-compile with x86_64-w64-mingw32-g++ -std=c++17 -O2 -static reference_network.cpp -o reference_network.exe
#include "hip_reference_network.h"
#include <iostream>
#include <chrono>
using namespace hip_reference;
int main(int argc,char**argv){try{
 if(argc<6){std::fprintf(stderr,"Usage: reference_network.exe ASSETS MODULES INPUT_RGBA_F32 NOISE_F32 OUTPUT_RGB_F32 [--720|--900|--1080] [--wmma] [--wave] [--tiled] [--fast-c32] [--fast-mh] [--fast-deep] [--fast-prefix] [--fused-c32] [--pooled] [--packed-weights] [--profile] [--repeat N] [--seed N] [--post-shift 0..3] [--dump DIR] [--history RGBA_F32] [--runtime 6|7]\nDefault processing grid: 512x512. --1080: 1920x1152. INPUT/history contain the full processing grid, RGBA floats. OUTPUT is RGB floats. Scalar validation graph: not a FPS benchmark.\n");return 2;}
 Options o;unsigned repeats=1;bool post_override=false;o.assets=argv[1];o.modules=argv[2];std::string hist;
 for(int i=6;i<argc;i++){std::string a=argv[i];if(a=="--packed-c32"){o.packed_c32=true;}else if(a=="--wall-profile"){o.wall_profile=true;}else if(a=="--packed-weights"){o.packed_weights=o.fast_mh=true;}else if(a=="--fused-ffn"){o.fast_c32=o.fused_ffn=true;}else if(a=="--fused-mh"){o.fast_mh=o.fused_mh=true;}else if(a=="--mh-wave"){o.fast_mh=o.mh_wave=true;}else if(a=="--fused-c32"){o.fast_c32=o.fused_c32=true;}else if(a=="--fast-mh"){o.fast_mh=true;}else if(a=="--fast-deep"){o.fast_deep=true;o.fast_vit=true;}else if(a=="--fast-prefix"){o.fast_prefix=true;}else if(a=="--fast-c32"){o.fast_c32=true;}else if(a=="--tiled"){o.tiled=true;}else if(a=="--wave"){o.wave=true;}else if(a=="--profile"){o.profile=true;}else if(a=="--pooled"){o.pooled=true;}else if(a=="--720"||a=="--900"){o.width=a=="--720"?1280:1600;o.height=a=="--720"?768:1024;o.fast_vit=true;if(!post_override)o.post_shift=3;}else if(a=="--wmma"){o.wmma=true;}else if(a=="--1080"){o.width=1920;o.height=1152;if(!post_override)o.post_shift=3;}else if((a=="--skip-blocks"||a=="--dump-only"||a=="--repeat"||a=="--post-shift"||a=="--seed"||a=="--dump"||a=="--history"||a=="--runtime")&&i+1<argc){std::string v=argv[++i];if(a=="--skip-blocks"){o.skip_blocks=ParseSkipBlocks(v);}else if(a=="--dump-only"){o.dump_only=v;}else if(a=="--repeat"){repeats=std::stoul(v);if(!repeats||repeats>100)throw std::runtime_error("repeat must be 1..100");}else if(a=="--post-shift"){auto n=std::stoul(v);if(n>3)throw std::runtime_error("post shift must be 0..3");o.post_shift=U(n);post_override=true;}else if(a=="--seed")o.seed=U(std::stoul(v));else if(a=="--dump")o.dump_dir=v;else if(a=="--history")hist=v;else{o.runtime=std::stoul(v);if(o.runtime!=6&&o.runtime!=7)throw std::runtime_error("runtime must be 6 or 7");}}else throw std::runtime_error("unknown/incomplete option: "+a);}
 auto load=[](const std::string&p){auto b=ReadBytes(p);if(b.size()%4)throw std::runtime_error("f32 alignment "+p);std::vector<float>f(b.size()/4);std::memcpy(f.data(),b.data(),b.size());return f;};
 auto input=load(argv[3]),noise=load(argv[4]),history=hist.empty()?std::vector<float>{}:load(hist);Network network(o);network.SetProgress([](const std::string&s){std::printf("stage %s\n",s.c_str());std::fflush(stdout);});auto start=std::chrono::steady_clock::now();auto out=network.Infer(input,noise,hist.empty()?nullptr:&history);auto elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::printf("iteration=0 wall_seconds=%.6f\n",elapsed);for(unsigned i=1;i<repeats;i++){start=std::chrono::steady_clock::now();out=network.Infer(input,noise,hist.empty()?nullptr:&history);elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::printf("iteration=%u wall_seconds=%.6f\n",i,elapsed);}std::ofstream f(argv[5],std::ios::binary);if(!f.write(reinterpret_cast<const char*>(out.data()),out.size()*4))throw std::runtime_error("output write failed");std::printf("reference complete extent=%ux%u floats=%zu wall_seconds=%.3f (includes allocations, uploads and synchronization)\n",o.width,o.height,out.size(),elapsed);network.PrintMemory();return 0;
 }catch(const std::exception&e){std::fprintf(stderr,"reference FAILED: %s\n",e.what());return 1;}}
